---
settings:
  name: ONTAP tools for VMware vSphere 9.13
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '9.13'
    url: "/ontap-tools-vmware-vsphere"
  - version-number: '9.12'
    url: "/ontap-tools-vmware-vsphere-912"
  - version-number: '9.11'
    url: "/ontap-tools-vmware-vsphere-911"
  - version-number: '9.10'
    url: "/ontap-tools-vmware-vsphere-910"
  - version-number: '9.8'
    url: "/ontap-tools-vmware-vsphere-98"
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documentation relative aux outils ONTAP pour VMware vSphere 9.13
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/release_notes.html"
  - section: concepts
  - section: deploy
  - section: configure
  - section: protect
  - section: manage
  - title: Mentions légales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Notes de mise à jour
      url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2886292
    - title: Découvrez les outils ONTAP pour VMware vSphere
      url: "/concepts/concept_virtual_storage_console_overview.html"
    - title: Outils ONTAP démarrage rapide
      url: "/qsg.html"
    - title: Déployez les outils ONTAP
      url: "/deploy/task_deploy_ontap_tools.html"
    - title: Mettez à niveau les outils ONTAP
      url: "/deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html"
  - title: Utilisez les outils ONTAP
    links:
    - title: Provisionner les datastores classiques
      url: "/configure/task_provision_datastores.html"
    - title: Provisionner des datastores vVols
      url: "/configure/task_provision_vvols_datastores.html"
    - title: Configurez le contrôle d'accès basé sur des rôles
      url: "/concepts/concept_vcenter_server_role_based_access_control_features_in_vsc_for_vmware_vsphere.html"
    - title: Configurer les diagnostics à distance
      url: "/manage/task_configure_vasa_provider_to_use_ssh_for_remote_diag_access.html"
    - title: Configurez la haute disponibilité
      url: "/concepts/concept_configure_high_availability_for_ontap_tools_for_vmware_vsphere.html"
  - title: Protéger et gérer les datastores
    links:
    - title: Protection des datastores
      url: "/protect/task_enable_storage_replication_adapter.html"
    - title: Protection des machines virtuelles
      url: "/protect/concept_configure_replication_for_vvols_datastore.html"
    - title: Surveiller les datastores classiques et les machines virtuelles
      url: "/manage/task_monitor_datastores_using_the_traditional_dashboard.html"
    - title: Surveillez les datastores vvols et les machines virtuelles
      url: "/manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html"
  - title: Ressources supplémentaires
    links:
    - title: Documentation relative aux versions antérieures des outils ONTAP pour
        VMware
      url: https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=63792
    - title: Base de connaissances NetApp - outils ONTAP
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/VSC_and_VASA_Provider
    - title: Utilitaire d'importation NetApp - vidéo
      url: https://www.youtube.com/watch?v=CEQmIEzNVfA
    - title: Communauté NetApp - Outils ONTAP
      url: https://community.netapp.com/t5/VMware-Solutions-Discussions/bd-p/vmware-solutions-discussions
