---
sidebar: sidebar 
permalink: qsg.html 
keywords: QSG, ONTAP tools for VMware vSphere, Quick start guide, Installing 
summary: 'Le fournit des instructions sur le déploiement et l"initialisation des outils ONTAP pour VMware vSphere.' 
---
= Aide à la vente des outils ONTAP pour VMware vSphere
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Les outils ONTAP pour VMware vSphere sont un plug-in vCenter Server unique qui comprend les extensions VSC, VASA Provider et Storage Replication adapter (SRA). VSC est recommandé pour tous les environnements ONTAP vSphere lors de la configuration des paramètres d'hôte ESXi et du provisionnement du stockage ONTAP en suivant les meilleures pratiques. Il est nécessaire de créer une application VASA Provider pour la prise en charge des volumes virtuels (vvols), et SRA fonctionne avec VMware site Recovery Manager.



== Préparation de l'installation

Vous déployez le plug-in en tant qu'appliance virtuelle, ce qui vous permet de réduire les efforts d'installation et d'enregistrement de chaque produit séparément auprès de vCenter Server.



=== De déploiement

Les outils ONTAP peuvent être utilisés avec Windows vCenter Server ou avec une appliance virtuelle VMware vCenter Server (vCSA). Vous devez déployer les outils ONTAP sur un système vSphere pris en charge incluant le système ESXi.

Les exigences minimales en matière d'espace et de dimensionnement de l'hôte sont les suivantes :

[cols="25,75"]
|===
| *Système* | *Exigences minimales* 


| Espace | 2.1 Go pour les installations à provisionnement fin, 54.0 Go pour les installations à provisionnement fin 


| Dimensionnement de l'hôte | Mémoire recommandée : 12 Go, processeurs recommandés : 2 
|===
Vous devez connaître les licences suivantes :

[cols="25,75"]
|===
| *Licence* | *Description* 


| SnapMirror | (Facultatif) requis pour la réalisation des opérations de basculement pour SRA et VASA Provider si u utilise la réplication vvols. 


| FlexClone | (Facultatif) requis pour les opérations de test de basculement pour SRA et pour les opérations vVvols de VASA Provider. 
|===
Les outils ONTAP utilisent les ports TCP bidirectionnels suivants :

|===
| * Exigences supplémentaires* | *Colonne Description* 


| 9083 | Lorsque cette option est activée, VASA Provider et SRA utilisent ce port pour communiquer avec vCenter Server. Ce port est également requis pour obtenir les paramètres TCP/IP. 


| 443 | En fonction de la façon dont vous avez configuré vos informations d'identification, VMware vCenter Server et les systèmes de stockage sont à l'écoute des communications sécurisées sur ce port. 


| 8143 | VSC écoute les communications sécurisées sur ce port. 


| 7 | VSC envoie une demande d'écho à ONTAP pour vérifier l'accessibilité. Elle n'est requise que lors de l'ajout d'un système de stockage et peut être désactivée par la suite. 
|===
Exigences minimales en matière de stockage et d'applications :

|===
| *Stockage, hôte et applications* | *Exigences de version* 


| ONTAP | ONTAP 9.3, 9.5, 9.6, 9.7, 9.8P1 ou version ultérieure. 


| VMware vSphere, vCenter Server, hôtes ESXi, site Recovery Manager (SRM), applications de plug-ins et bases de données colonne 1 | Voir la https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Matrice d'interopérabilité"^] 
|===


=== Configuration minimale requise pour les outils ONTAP

* Configurez et configurez votre environnement vCenter Server.
* Téléchargez le fichier .ova.
* Les informations d'identification de votre instance de vCenter Server.
* Supprimez le cache du navigateur pour éviter tout problème de cache du navigateur pendant le déploiement des outils ONTAP.
* Configurez la passerelle par défaut à utiliser par l'appliance virtuelle pour répondre aux requêtes ping ICMP.
* Nom d'hôte DNS valide pour l'appliance virtuelle.
* Téléchargez et installez OnCommand API Services pour ONTAP 9.6 ou version antérieure si vous souhaitez visualiser le tableau de bord vvols. Il n'est pas nécessaire d'enregistrer des services d'API OnCommand auprès de VASA Provider si vous utilisez ONTAP 9.7 ou une version ultérieure.




=== Exigences facultatives pour SRA

Si vous déployez l'appliance virtuelle pour une utilisation avec VMware site Recovery Manager, vous devez avoir : * téléchargé le `.msi` Fichier du plug-in SRA uniquement si vous souhaitez configurer la solution de reprise après incident site Recovery Manager (SRM). Colonne 1 * téléchargé le `.tar.gz` Fichier pour SRA si vous utilisez l'appliance SRM.



== Déploiement des outils ONTAP

.Étapes
. Téléchargez le `.ova` fichier du https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Site de support NetApp"^] Sur un système vSphere client pour déployer les outils ONTAP.
+
Vous devez déployer le `.ova` Fichier sur les sites source et de destination si vous déployez SRA.

. Connectez-vous au client Web vSphere, sélectionnez *Accueil* > *hôte et clusters*.
. Cliquez avec le bouton droit de la souris sur le centre de données requis, puis cliquez sur *déployer le modèle OVF*.
. Vous pouvez soit saisir l'URL du fichier .ova, soit rechercher le dossier dans lequel le fichier .ova est enregistré, puis cliquer sur *Suivant*.
. Entrez les informations requises pour terminer le déploiement.
+

NOTE: (Facultatif) si vous souhaitez créer des conteneurs sans vous inscrire à vCenter Server, cochez la case Activer VMware Cloud Foundation (VCF) dans la section configurer vCenter ou Activer VCF.



Vous pouvez afficher la progression du déploiement à partir de l'onglet *tâches* et attendre la fin du déploiement.



=== Déployer SRA sur SRM

Vous pouvez déployer SRA sur le serveur Windows SRM ou sur l'appliance 8.2 SRM.



==== Installation de SRA sur le serveur Windows SRM

.Étapes
. Téléchargez le `.msi` Installateur du plug-in SRA accessible depuis le site du support NetApp.
. Double-cliquez sur le téléchargé `.msi` Installer le plug-in SRA et suivre les instructions à l'écran.
. Entrez l'adresse IP et le mot de passe de votre appliance virtuelle déployée pour terminer l'installation du plug-in SRA sur le serveur SRM.




==== Téléchargement et configuration de SRA sur SRM Appliance

.Étapes
. Téléchargez le `.tar.gz` fichier du https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Site de support NetApp"^].
. Sur l'écran SRM Appliance, cliquez sur *Storage Replication adapter* > *New adapter*.
. Téléchargez le `.tar.gz` Fichier vers SRM.
. Relancez l'analyse des cartes pour vérifier que les détails sont mis à jour dans la page SRM Storage Replication Adapters.
. Connectez-vous à l'aide du compte administrateur à l'appliance SRM à l'aide de la fonction putty.
. Passez à l'utilisateur root : `su root`
. Dans la commande log location, entrez pour obtenir l'ID docker utilisé par docker SRA : `docker ps -l`
. Connectez-vous à l'ID de conteneur : `docker exec -it -u srm <container id> sh`
. Configurer SRM à l'aide de l'adresse IP et du mot de passe des outils ONTAP : `perl command.pl -I <otv-IP> administrator <otv-password>`Un message de confirmation de la mémorisation des identifiants de stockage s'affiche.




==== Mise à jour des informations d'identification SRA

.Étapes
. Supprimez le contenu du répertoire /srm/sra/conf en utilisant :
+
.. `cd /srm/sra/conf`
.. `rm -rf *`


. Exécutez la commande perl pour configurer SRA avec les nouvelles informations d'identification :
+
.. `cd /srm/sra/`
.. `perl command.pl -I <otv-IP> administrator <otv-password>`






==== Activation de VASA Provider et SRA

.Étapes
. Connectez-vous au client Web vSphere en utilisant l'adresse IP que vous avez spécifiée lors du déploiement.
. Cliquez sur l'icône *OTV* et entrez le nom d'utilisateur et le mot de passe spécifiés pendant le déploiement, puis cliquez sur *connexion*.
. Dans le volet gauche d'OTV, *Paramètres > Paramètres d'administration > gérer les fonctionnalités* et activez les fonctionnalités requises.
+

NOTE: Vasa Provider est activé par défaut. Si vous souhaitez utiliser la capacité de réplication pour les datastores vVvols, utilisez ensuite le bouton bascule Activer la réplication vvols.

. Entrez l'adresse IP des outils ONTAP et le mot de passe administrateur, puis cliquez sur *appliquer*.

