---
permalink: deploy/concept_supported_storage_system_and_applications.html 
sidebar: sidebar 
keywords:  
summary: Avant de commencer à déployer les outils ONTAP pour VMware vSphere, il est recommandé de connaître les exigences de base du système de stockage, les exigences des applications et les exigences de licence. 
---
= Système de stockage pris en charge, licences et applications pour les outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de commencer à déployer les outils ONTAP pour VMware vSphere, il est recommandé de connaître les exigences de base du système de stockage, les exigences des applications et les exigences de licence.

La matrice d'interopérabilité (IMT) contient les dernières informations sur les versions prises en charge de ONTAP, vCenter Server, les hôtes ESXi, les applications de plug-in et site Recovery Manager (SRM).

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Matrice d'interopérabilité"^]

Vous devez activer la licence FlexClone pour la réalisation d'opérations de snapshots de machines virtuelles et de clonage pour les datastores VMware Virtual volumes (vvols).

Storage Replication adapter (SRA) nécessite les licences suivantes :

* Licence SnapMirror
+
Vous devez activer la licence SnapMirror pour effectuer les opérations de basculement pour SRA.

* Licence FlexClone
+
Vous devez activer la licence FlexClone pour réaliser les opérations de basculement pour SRA.



Pour afficher les IOPS d'un datastore, vous devez activer le contrôle des E/S du stockage ou décocher la case Désactiver la collecte des statistiques d'E/S du stockage dans la configuration du contrôle des E/S du stockage. Vous pouvez activer le contrôle des E/S de stockage uniquement si vous disposez de la licence Enterprise plus de VMware.

* https://kb.vmware.com/s/article/1022091["Dépannage du contrôle d'E/S du stockage"]
* https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/6-5/vsphere-resource-management-6-5.html["Gestion des ressources vSphere"]

