---
permalink: deploy/reference_considerations_for_deploying_virtual_appliance_for_vsc_vasa_provider_and_sra.html 
sidebar: sidebar 
keywords: Virtual Storage Console,Storage Replication Adapter 
summary: Avant de déployer les outils ONTAP pour VMware vSphere, il est conseillé de planifier votre déploiement et de choisir comment configurer les outils ONTAP dans votre environnement. 
---
= Considérations relatives au déploiement des outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de déployer les outils ONTAP pour VMware vSphere, il est conseillé de planifier votre déploiement et de choisir comment configurer les outils ONTAP dans votre environnement.

Le tableau suivant présente les éléments à prendre en compte avant de déployer les outils ONTAP.

|===


| *Considérations* | *Description* 


 a| 
Premier déploiement des outils ONTAP
 a| 
Le déploiement des outils ONTAP pour VMware vSphere installe automatiquement les fonctionnalités des outils ONTAP.

link:../deploy/concept_installation_workflow_for_new_users.html["Flux de travail de déploiement pour les nouveaux utilisateurs des outils ONTAP pour VMware vSphere"]



 a| 
Mise à niveau à partir d'un déploiement existant des outils ONTAP
 a| 
La procédure de mise à niveau à partir d'un déploiement existant des outils ONTAP vers les outils ONTAP dépend de la version des outils ONTAP et du déploiement des outils ONTAP. La section flux de travail de déploiement et mise à niveau contient plus d'informations.

link:concept_installation_workflow_for_existing_users_of_vsc.html["Workflow de déploiement pour les utilisateurs existants des outils ONTAP"]

Meilleures pratiques avant la mise à niveau :

* Vous devez enregistrer des informations sur les systèmes de stockage utilisés et leurs identifiants.
+
Après la mise à niveau, vérifiez que tous les systèmes de stockage ont été automatiquement découverts et qu'ils disposent des informations d'identification appropriées.

* Si vous avez modifié l'un des rôles d'outils ONTAP standard, vous devez copier ces rôles pour enregistrer vos modifications.
+
Les outils ONTAP remplacent les rôles standard par les valeurs par défaut actuelles chaque fois que vous redémarrez le service d'outils ONTAP.





 a| 
Régénération d'un certificat SSL pour les outils ONTAP
 a| 
Le certificat SSL est automatiquement généré lorsque vous déployez les outils ONTAP. Vous devrez peut-être régénérer le certificat SSL pour créer un certificat spécifique au site.

link:../configure/task_regenerate_an_ssl_certificate_for_vsc.html["Régénérer un certificat SSL pour Virtual Storage Console"]



 a| 
Définition des valeurs du serveur VMware ESXi
 a| 
Bien que la plupart des valeurs de votre serveur ESXi soient définies par défaut, il est recommandé de vérifier les valeurs. Ces valeurs sont basées sur des tests internes. Selon votre environnement, vous devrez peut-être modifier certaines valeurs pour améliorer les performances.

* link:../configure/task_configure_esx_server_multipathing_and_timeout_settings.html["Configurer les paramètres de chemins d'accès multiples et de délai d'attente du serveur ESXi"]
* link:../configure/reference_esxi_host_values_set_by_vsc_for_vmware_vsphere.html["Valeurs de l'hôte ESXi définies à l'aide des outils ONTAP pour VMware vSphere"]




 a| 
Valeurs de temporisation du système d'exploitation invité
 a| 
Les scripts d'expiration du délai d'attente du système d'exploitation invité (OS invité) définissent les valeurs d'expiration du délai d'E/S SCSI pour les systèmes d'exploitation invités Linux, Solaris et Windows pris en charge pour fournir un comportement de basculement correct.

|===
Le tableau ci-dessous présente le besoin pour configurer les outils ONTAP.

|===


| *Considérations* | *Description* 


 a| 
Exigences du contrôle d'accès basé sur des rôles (RBAC)
 a| 
Les outils ONTAP prennent en charge le RBAC vCenter Server et ONTAP RBAC. Compte utilisé pour enregistrer les outils ONTAP sur le serveur vCenter (`\https://<appliance_ip>:8143/Register.html`) Doit être un administrateur vCenter Server (affecté à l'administrateur vCenter Server ou au rôle d'administrateur). Si vous prévoyez d'exécuter les outils ONTAP pour VMware vSphere en tant qu'administrateur, vous devez disposer de toutes les autorisations et privilèges requis pour toutes les tâches.

Si votre entreprise exige que vous restreignez l'accès aux objets vSphere, vous pouvez créer et attribuer des rôles d'outils ONTAP standard aux utilisateurs pour répondre aux exigences du serveur vCenter.

Vous pouvez créer les rôles ONTAP recommandés en utilisant ONTAP System Manager à l'aide du fichier JSON fourni avec les outils ONTAP.

Si un utilisateur tente d'effectuer une tâche sans les privilèges et autorisations appropriés, les options de tâche sont grisées.

* link:../concepts/concept_standard_roles_packaged_with_virtual_appliance_for_vsc_vp_and_sra.html["Rôles standard fournis avec les outils ONTAP"]
* link:../concepts/concept_ontap_role_based_access_control_feature_for_ontap_tools.html["Autorisations pour les systèmes de stockage ONTAP et les objets vSphere"]




 a| 
Version ONTAP
 a| 
Vos systèmes de stockage doivent exécuter ONTAP 9.7, 9.8P1 ou une version ultérieure.



 a| 
Profils de capacité de stockage
 a| 
Pour utiliser des profils de capacité de stockage ou configurer des alarmes, vous devez activer VASA Provider pour ONTAP. Une fois VASA Provider activé, vous pouvez configurer les datastores VMware Virtual volumes (vvols). Vous pouvez également créer et gérer des profils et des alarmes de capacité de stockage. Les alarmes vous avertissent lorsqu'un volume ou un agrégat est à presque pleine capacité ou lorsqu'un datastore n'est plus conforme au profil de capacité de stockage associé.

|===