---
permalink: deploy/reference_port_requirements_for_vsc.html 
sidebar: sidebar 
keywords: port requirements 
summary: 'Par défaut, Virtual Storage Console \(VSC\) utilise des ports désignés pour permettre la communication entre ses composants, notamment les systèmes de stockage et VMware vCenter Server. Si les pare-feu sont activés, vous devez vous assurer que les pare-feu sont définis de manière à autoriser les exceptions.' 
---
= Configuration requise pour les ports VSC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Par défaut, Virtual Storage Console (VSC) utilise des ports désignés pour permettre la communication entre ses composants, notamment les systèmes de stockage et VMware vCenter Server. Si les pare-feu sont activés, vous devez vous assurer que les pare-feu sont définis de manière à autoriser les exceptions.

Pour les pare-feu autres que Windows, vous devez autoriser manuellement l'accès à des ports spécifiques utilisés par VSC. Si vous n'autorisez pas l'accès à ces ports, un message d'erreur tel que ce qui suit s'affiche.

`Unable to communicate with the server.`

VSC utilise les ports TCP bidirectionnels suivants :

|===


| *Numéro de port par défaut* | *Description* 


 a| 
9083
 a| 
Lorsqu'il est activé, le fournisseur VASA et l'adaptateur SRA (Storage Replication adapter) utilisent ce port pour communiquer avec vCenter Server. Ce port est également requis pour obtenir les paramètres TCP/IP. Ce port est utilisé pour télécharger le pack de prise en charge VP, accéder à l'interface utilisateur Web-CLI et contrôler la communication du chemin de VMware vers VP.



 a| 
443
 a| 
En fonction de la façon dont vous avez configuré vos informations d'identification, VMware vCenter Server et les systèmes de stockage sont à l'écoute des communications sécurisées sur ce port. Le port est utilisé dans l'architecture de communication client-serveur. Le port 443 est activé par défaut pour les connexions sécurisées. Le client, qui peut être n'importe quel client d'automatisation utilisant l'API REST, initie la connexion au serveur et les points d'extrémité échangent des données.



 a| 
8143
 a| 
VSC écoute les communications sécurisées sur ce port. Le port est utilisé dans l'architecture de communication client-serveur. Le client, qui peut être n'importe quel client d'automatisation utilisant l'API REST, initie la connexion au serveur et les points d'extrémité échangent des données. Ce port est activé pour les services VSC et pour l'exportation des journaux du serveur VSC. La page register.html est hébergée sur ce port. Le RESTE de l'andaineur est exposé sur ce port.

|===

NOTE: Vous devez avoir activé le protocole ICMP (Internet Control message Protocol) avant de déployer les outils ONTAP.

Si ICMP est désactivé, la configuration initiale des outils ONTAP échoue et VSC ne peut pas démarrer les services VSC et VASA Provider après le déploiement. Vous devez activer manuellement les services VSC et VASA Provider après le déploiement.
