---
permalink: deploy/reference_deployment_customization_requirements.html 
sidebar: sidebar 
keywords:  
summary: Vous devez tenir compte de quelques restrictions, tout en personnalisant les outils ONTAP de déploiement. 
---
= Personnalisation du déploiement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez tenir compte de quelques restrictions, tout en personnalisant les outils ONTAP de déploiement.



== Mot de passe utilisateur administrateur de l'appliance

Vous ne devez pas utiliser d'espace dans le mot de passe administrateur.



== Identifiants de la console de maintenance de l'appliance

Vous devez accéder à la console de maintenance en utilisant le nom d'utilisateur "maaint". Vous pouvez définir le mot de passe pour l'utilisateur "saint" pendant le déploiement. Vous pouvez utiliser le menu Configuration de l'application de la console de maintenance de vos outils ONTAP pour modifier le mot de passe.



== Informations d'identification de l'administrateur vCenter Server

Vous pouvez définir les informations d'identification d'administrateur pour vCenter Server lors du déploiement des outils ONTAP.

Si le mot de passe du serveur vCenter change, vous pouvez mettre à jour le mot de passe de l'administrateur à l'aide de l'URL suivante : \https://<IP>:8143/Register.html où l'adresse IP est des outils ONTAP que vous fournissez pendant le déploiement.



== Adresse IP du serveur vCenter

* Vous devez indiquer l'adresse IP (IPv4 ou IPv6) de l'instance de vCenter Server à laquelle vous souhaitez enregistrer les outils ONTAP.
+
Le type d'outils ONTAP et de certificats VASA générés dépend de l'adresse IP (IPv4 ou IPv6) que vous avez fournie pendant le déploiement. Lors du déploiement des outils ONTAP, si vous n'avez pas saisi de détails IP statiques et si votre DHCP alors le réseau fournit à la fois des adresses IPv4 et IPv6.

* L'adresse IP des outils ONTAP utilisée pour s'enregistrer auprès de vCenter Server dépend du type d'adresse IP du serveur vCenter (IPv4 ou IPv6) saisi dans l'assistant de déploiement.
+
Les outils ONTAP et les certificats VASA sont générés à l'aide du même type d'adresse IP que celui utilisé lors de l'enregistrement du serveur vCenter.

+

NOTE: : IPv6 est pris en charge uniquement avec vCenter Server 6.7 et versions ultérieures.





== Propriétés du réseau de l'appliance

Si vous n'utilisez pas DHCP, spécifiez un nom d'hôte DNS valide (non qualifié) ainsi que l'adresse IP statique pour les outils ONTAP et les autres paramètres réseau. Tous ces paramètres sont nécessaires pour une installation et un fonctionnement corrects.
