---
permalink: deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords: Virtual Storage Console, Storage Replication Adapter 
summary: Vous pouvez effectuer une mise à niveau sur place vers la dernière version des outils ONTAP à partir de votre configuration 9.10 ou ultérieure existante en suivant les instructions fournies ici. 
---
= Passez à la dernière version des outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer une mise à niveau sur place vers la dernière version des outils ONTAP depuis votre version 9.10 ou ultérieure existante en suivant les instructions fournies ici.

*Ce dont vous aurez besoin*

* Vous devez avoir téléchargé le fichier _.iso_ pour la dernière version des outils ONTAP.
* Vous devez avoir réservé au moins 12 Go de RAM pour que les outils ONTAP fonctionnent de façon optimale après la mise à niveau.
* Vous devez nettoyer le cache du navigateur vSphere client.
+
link:../deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html["Effacez les packages de plug-in téléchargés dans le cache vSphere"]



Effectuer les étapes suivantes pour valider le fichier _.iso_ si nécessaire. Cette étape est facultative :

. Extrayez la clé publique du certificat de signature de code émis par Entrust (OTV_ISO_CERT.pem) openssl x509 -in OTV_ISO_CERT.pem -pubkey -noout > csc-prod-OTV-SRA-TGZ.pub
. Vérifiez la signature dans le Digest à l'aide de la clé publique (cette étape doit se produire dans le système utilisateur final avant d'installer le binaire. Un bundle de certificats doit être inclus dans le package de déploiement)
+
openssl dgst -sha256 -verify csc-prod-OTV-SRA-TGZ.pub -signature netapp-ontap-Tools-for-vmware-vsphere-9.12-9327-upgrade-iso.SIG netapp-ontap-tools-for-vmware-vsphere-9.12-9327-upgrade.iso



Après la mise à niveau, l'état de VASA Provider depuis le déploiement existant est conservé. Vous devez activer ou désactiver manuellement VASA Provider en fonction de vos besoins après la mise à niveau. Cependant, il est recommandé d'activer VASA Provider, même si VMware Virtual volumes (vvols) n'est pas utilisé, car il permet de gérer les profils de capacité de stockage pour le provisionnement classique des datastores, et les alarmes de stockage.


NOTE: Vous pouvez effectuer une mise à niveau sans déplacement des outils ONTAP vers la dernière version d'uniquement à partir de vos versions 9.10 ou ultérieures existantes.


NOTE: Dans le cadre de la mise à niveau des outils ONTAP 9.12, tous les processus d'authentification et de communication des systèmes de stockage sont remplacés par une authentification de base et une authentification basée sur certificat en faisant confiance automatiquement aux certificats de stockage ONTAP. Aucune action n'est requise de la part de l'utilisateur.

L'ajout d'un système de stockage sans authentification par certificat est restreint.

Si le système de stockage est ajouté avec un utilisateur personnalisé créé dans le périmètre du cluster à l'aide du fichier json et que vous souhaitez effectuer une mise à niveau vers la version 9.12, alors
Exécutez les commandes ci-dessous sur l'interface de ligne de commande ONTAP avant de procéder à la mise à niveau pour activer la communication basée sur des certificats entre les outils ONTAP pour VMware vSphere et ONTAP.

. _security login role create -role <existing-role-name> -cmddirname "security login show" -access all_
. _security login role create -role <existing-role-name> -cmddirname "security certificate show" -access all_
. _security login role create -role <existing-role-name> -cmddirname "security certificate install" -access all_


Si le système de stockage est ajouté avec un utilisateur scoped SVM créé personnalisé en utilisant le fichier json et que vous souhaitez effectuer une mise à niveau vers 9.12, Exécutez ensuite les commandes ci-dessous sur l'interface de ligne de commande ONTAP avec un accès administrateur du cluster avant la mise à niveau pour activer la communication basée sur le certificat entre les outils ONTAP pour VMware vSphere et ONTAP :

. _security login role create -role <existing-role-name> -cmddirname "security certificate install" -access all -vserver <vserver-name>_
. _security login role create -role <existing-role-name> -cmddirname "security certificate show" -access all -vserver <vserver-name>_
. _security login create -user-or-group-name <user> -application http -authentication-method cert -role <existing-role-name> -vserver <vserver-name>_
. _security login create -user-or-group-name <user> -application ontapi -authentication-method cert -role <existing-role-name> -vserver <vserver-name>_


*Étapes*

. Montez le fichier _.iso_ téléchargé sur les outils ONTAP :
+
.. Cliquez sur *Modifier les paramètres* > *lecteur DVD/CD-ROM*.
.. Sélectionnez le fichier *datastore ISO* dans la liste déroulante.
.. Recherchez et sélectionnez le fichier _.iso_ téléchargé, puis cochez la case *se connecter à la mise sous tension*.


. Accédez à l'onglet Récapitulatif des outils ONTAP déployés.
. Démarrez la console de maintenance.
. À l'invite "Menu principal", entrez option `2` Pour *Configuration du système*, puis entrez option `8` Pour *Upgrade*.
+
Une fois la mise à niveau terminée, les outils ONTAP redémarre. Les outils ONTAP sont enregistrés sur le serveur vCenter avec la même adresse IP qu'avant la mise à niveau.

. Si vous souhaitez que les outils ONTAP soient enregistrés auprès du serveur vCenter avec l'adresse IPv6, vous devez effectuer les opérations suivantes :
+
.. Annuler l'inscription des outils ONTAP.
.. Enregistrez l'adresse IPv6 des outils ONTAP dans vCenter Server à l'aide de la page *Inscription*.
.. Régénérez les outils ONTAP et les certificats VASA Provider après l'enregistrement.


+

IMPORTANT: IPv6 est pris en charge uniquement avec vCenter Server 6.7 et versions ultérieures.

. Déconnectez-vous puis reconnectez-vous au client vSphere pour afficher les outils ONTAP déployés.
+
.. Déconnectez-vous de votre client Web vSphere ou de vSphere client existant et fermez la fenêtre.
.. Connectez-vous au client vSphere.
+
La mise à jour du plug-in peut prendre quelques minutes dans le client vSphere.





[NOTE]
====
* Si vous procédez à la mise à niveau de la version 7.0 des outils ONTAP vers la dernière version des outils ONTAP, vous devez d'abord créer des profils de capacité de stockage avant de tenter de modifier une stratégie de stockage de machine virtuelle existante, ou si vous obtenez une erreur indiquant que les valeurs sont incorrectes ou manquantes.
* Si vous effectuez une mise à niveau d'une version antérieure vers la dernière version des outils ONTAP, vous trouverez que le `vvol.rebalance.threshold` la propriété est manquante dans le fichier `vvol.properties.
+
La valeur par défaut de la propriété est définie sur 85 %.

* Le déploiement fonctionnera toujours après la mise à niveau vers la dernière version des outils ONTAP pour laquelle FIPS est activé, mais avec une ancienne version de vCenter pour laquelle FIPS n'est pas pris en charge. Cependant, si vous mettez à niveau vCenter vers la dernière version prise en charge par FIPS et que vous disposez d'une version antérieure des outils ONTAP, le déploiement ne fonctionnera que si FIPS est désactivé sur vCenter.


====