---
permalink: deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html 
sidebar: sidebar 
keywords:  
summary: 'La fonctionnalité VASA Provider est activée par défaut dans les outils ONTAP pour VMware vSphere. Vous pouvez configurer des datastores VMware Virtual volumes \(vVvols\) avec des profils de capacité de stockage requis pour chaque datastore vvols.' 
---
= Activez VASA Provider pour la configuration des datastores virtuels
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La fonctionnalité VASA Provider est activée par défaut dans les outils ONTAP pour VMware vSphere. Il est possible de configurer des datastores VMware Virtual volumes (vvols) avec les profils de capacité de stockage requis pour chaque datastore vvols.

*Ce dont vous aurez besoin*

* Vous devez avoir configuré votre instance vCenter Server et ESXi.
* Vous devez avoir déployé des outils ONTAP .


*À propos de cette tâche*

Si la fonctionnalité VASA Provider est désactivée avant la mise à niveau vers la version 9.7.1 des outils ONTAP , la fonctionnalité VASA Provider reste désactivée après la mise à niveau. Cette version vous permet d'activer la fonctionnalité de réplication de vvols pour les datastores vvols.

*Étapes*

. Connectez-vous à l'interface utilisateur Web de VMware vSphere.
. Dans vSphere client, cliquez sur *Menu* > *ONTAP Tools Console*.
. Cliquez sur *Paramètres*.
. Cliquez sur *gérer les fonctionnalités* dans l'onglet Paramètres d'administration.
. Dans la boîte de dialogue gérer les fonctionnalités, sélectionnez l'extension VASA Provider à activer.
. Si vous souhaitez utiliser la capacité de réplication pour les datastores vVvols, utilisez le bouton bascule *Activer la réplication vVvols*.
. Entrez l'adresse IP des outils ONTAP et le mot de passe administrateur, puis cliquez sur *appliquer*.
+

NOTE: Si l'état de VASA Provider s'affiche en tant que « hors ligne » même après l'activation de l'extension VASA Provider, vérifiez alors le ``/var/log/vmware/vmware-sps/sps.log` File pour toute erreur de connexion avec VASA Provider ou redémarrez le service « vmware-sps ».





== Enregistrez les services de l'API OnCommand avec ONTAP 9.6 ou une version antérieure

Si vous utilisez ONTAP 9.6 ou une version antérieure, le tableau de bord vvols peut afficher les détails des datastores VMware Virtual volumes (vvols) et des machines virtuelles uniquement si vous avez enregistré OnCommand API Services pour VASA Provider pour obtenir des données pour les rapports vVvols VM et datastore.

*Ce dont vous aurez besoin*

Vous devez avoir téléchargé les services d'API OnCommand version 2.1 ou ultérieure depuis le site de support NetApp.


NOTE: Le tableau de bord vVvols affiche les indicateurs de performances uniquement lorsque les datastores et les machines virtuelles SAN vvols sont configurés à l'aide de ONTAP 9.3 ou version ultérieure.

*Étapes*

. Dans la page d'accueil des outils ONTAP, cliquez sur *Paramètres*.
. Cliquez sur *gérer l'extension* dans l'onglet Paramètres d'administration.
. Utilisez le curseur Enregistrer les services d'API OnCommand pour activer les services d'API OnCommand.
. Saisissez l'adresse IP, le port de service et les informations d'identification des services d'API OnCommand.
+
Vous pouvez également utiliser la boîte de dialogue gérer les extensions VASA Provider pour les modifications suivantes :

+
** Pour mettre à jour l'enregistrement des services d'API OnCommand en cas de modification des informations d'identification.
** Pour annuler l'enregistrement de OnCommand API Services lorsque vous n'avez plus besoin du tableau de bord vvols.
+
Vous devez décocher la case Enregistrer les services d'API OnCommand pour supprimer l'enregistrement des services d'API OnCommand pour VASA Provider.



. Cliquez sur *appliquer*.
+
Le tableau de bord vVvols affiche les metrics pour les datastores ONTAP 9.6 ou antérieurs SAN vvols uniquement après l'enregistrement des services API OnCommand.



*Informations connexes*

https://mysupport.netapp.com/site/global/dashboard["Support NetApp"]
