---
permalink: deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html 
sidebar: sidebar 
keywords: clean up browser cache 
summary: Si les plug-ins ne sont pas mis à jour automatiquement après le déploiement ou la mise à niveau des outils ONTAP, nettoyez les modules du plug-in de téléchargement mis en cache sur le navigateur et, sur le serveur vCenter, résolvez les problèmes de plug-in vCenter Server. 
---
= Effacez les packages de plug-in téléchargés dans le cache vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si les plug-ins ne sont pas mis à jour automatiquement après le déploiement ou la mise à niveau des outils ONTAP, nettoyez les modules du plug-in de téléchargement mis en cache sur le navigateur et sur le serveur vCenter pour résoudre les problèmes de plug-in vCenter Server.

*Étapes*

. Déconnexion de votre client web vSphere ou de vSphere client existant.
. Retirez le cache du navigateur.
. Supprimez les modules du plug-in en cache du client vSphere.
+
|===


| *Si vous utilisez...* | *Effectuez les opérations suivantes...* 


 a| 
Serveur Windows vCenter
 a| 
Supprimez les dossiers suivants `com.netapp.vasa.vvol.webclient-x.x.x.xxxx`, `com.netapp.nvpf.webclient-x.x.x.xxxx`, et `com.netapp.vsch5-x.x.x.xxxx` situé à :

** Chemin du client Web vSphere : `C:\ProgramData\VMware\vCenterServer\cfg\vsphere-client\vc-packages\vsphere-client-serenity`
** Chemin du client vSphere (HTML5) : `C:\ProgramData\VMware\vCenterServer\cfg\vsphere-ui\vc-packages\vsphere-client-serenity`




 a| 
VCSA
 a| 
.. SSH dans l'appliance VCSA.
.. Accédez au répertoire des extensions de l'interface utilisateur du client Web vCenter à l'aide de `cd /etc/vmware/vsphere-client/vc-packages/vsphere-client-serenity`
.. Supprimez les modules de plug-ins en cache propres à NetApp à l'aide du `rm -rf` Commandes : exemple : ici x.x.x.xxxx est la version de votre plug-in. ---- rm -rf com.netapp.vasa.vvol.webclient-x.x.x.xxxx rm -rf com.netapp.nvpf.webclient-x.x.x.xxxx rm -rf com.netapp.vsch5-x.x.x.xxxx ----
.. Modifiez les répertoires dans le répertoire des extensions de l'interface utilisateur du client vCenter (HTML5) à l'aide de `cd /etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity`
.. Supprimez les packs de plug-ins mis en cache spécifiques au plug-in NetApp à l'aide du `rm -rf` Commandes: Exemple: Ici x.x.x.xxxx est la version de votre plug-in --- RM -rf com.netapp.vasa.vvol.webclient-x.x.x.xxxx RM -rf com.netapp.nvpf.webclient-x.x.x.xxxx RM -rf com.netapp.vsch5-x.x.x.xxxx ------


|===
. Connectez-vous à vSphere et redémarrez le client Web vSphere et les services du client vSphere à l'aide des commandes suivantes :
+
[listing]
----
service-control --stop vsphere-client vsphere-ui
service-control --start vsphere-client vsphere-ui
----

