---
permalink: protect/concept_migration_of_disaster_recovery_setup_from_windows_to_appliance.html 
sidebar: sidebar 
keywords: Migration 
summary: 'Si vous utilisez le Gestionnaire de reprise sur site Windows \(SRM\) pour la reprise après incident et que vous souhaitez utiliser l"appliance SRM pour la même configuration, vous devez migrer la configuration de la reprise après incident Windows vers la solution SRM basée sur l"appliance.' 
---
= Migration de Windows SRM vers l'appliance SRM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez Windows site Recovery Manager (SRM) pour la reprise après incident et que vous souhaitez utiliser l'appliance SRM pour la même configuration, vous devez migrer la configuration de la reprise après incident Windows vers la solution SRM basée sur l'appliance.

Les étapes de la migration de la reprise sur incident sont les suivantes :

. Mettez à niveau vos outils ONTAP pour l'appliance VMware vSphere vers la dernière version.
+
link:../deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html["Passez à la dernière version des outils ONTAP"]

. Migration de l'adaptateur de réplication du stockage Windows vers l'appliance SRA.
. Migrez les données Windows SRM vers l'appliance SRM.


Voir https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/site-recovery-manager/8-8/site-recovery-manager-installation-and-configuration-8-8.html["Installation et configuration de site Recovery Manager"] pour les étapes détaillées
