---
permalink: protect/configure_sra_with_srm_shared_site.html 
sidebar: sidebar 
keywords: SRA with SRM 
summary: Les outils ONTAP pour VMware vSphere prennent en charge la configuration du site de restauration partagée VMware SRM. 
---
= Configurez SRA avec SRM dans une configuration de site de reprise partagé
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les outils ONTAP pour VMware vSphere prennent en charge la configuration du site de restauration partagée SRM de VMware. Pour plus d'informations, voir :  https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/site-recovery-manager/8-8/site-recovery-manager-installation-and-configuration-8-8.html["Site Recovery Manager dans une configuration de site de reprise partagé"]. Les instances de site Recovery Manager Server du site de reprise se connectent aux mêmes instances de vCenter Server.

Dans une configuration de site de restauration partagée SRM, chaque serveur SRM doit disposer d'une instance SRA dédiée (relation 1:1 entre SRM et SRA). Configurez OTV en mode VCF pour qu'il agisse en tant qu'instance SRA dédiée pour chaque serveur SRM. Vous pouvez également déployer des outils ONTAP pour l'appliance VMware vSphere qui ne sont pas compatibles SRA et qui sont enregistrés dans vCenter et utilisés pour les tâches non SRA, telles que le provisionnement des datastores.

Le https://kb.netapp.com/mgmt/OTV/SRA/Storage_Replication_Adapter%3A_How_to_configure_SRA_in_a_SRM_Shared_Recovery_Site["Comment configurer SRA sur un site de reprise partagé SRM"] L'article de la base de connaissances détaille la procédure de configuration de SRA pour prendre en charge la configuration du site de récupération partagée SRM.
