---
permalink: protect/reference_configure_storage_replication_adapter_for_highly_scaled_environment.html 
sidebar: sidebar 
keywords:  
summary: 'Vous devez configurer les intervalles d"expiration du stockage en fonction des paramètres recommandés pour l"adaptateur de réplication du stockage \(SRA\) afin de réaliser de manière optimale dans les environnements à grande échelle.' 
---
= Configurer Storage Replication adapter pour un environnement à grande échelle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez configurer les intervalles d'expiration du stockage en fonction des paramètres recommandés pour Storage Replication adapter (SRA) afin de bénéficier de performances optimales dans les environnements à grande échelle.



== Paramètres du fournisseur de stockage

Vous devez définir les valeurs de délai suivantes sur SRM pour l'environnement mis à l'échelle :

|===


| *Paramètres avancés* | *Valeurs de temporisation* 


 a| 
`StorageProvider.resignatureTimeout`
 a| 
Augmentez la valeur du réglage de 900 à 12000 secondes.



 a| 
`storageProvider.hostRescanDelaySec`
 a| 
60



 a| 
`storageProvider.hostRescanRepeatCnt`
 a| 
20



 a| 
`storageProvider.hostRescanTimeoutSec`
 a| 
Définir une valeur élevée (par exemple : 99999)

|===
Vous devez également activer le `StorageProvider.autoResignatureMode` option.

Pour plus d'informations sur la modification des paramètres du fournisseur de stockage, reportez-vous à la documentation Broadcom.

https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/site-recovery-manager/8-8/site-recovery-manager-administration-8-8/advanced-srm-configuration/reconfigure-srm-settings/change-storage-provider-settings.html["Modifier les paramètres du fournisseur de stockage"]



== Paramètres de stockage

Lorsque vous appuyez sur une temporisation, augmentez les valeurs de `storage.commandTimeout` et `storage.maxConcurrentCommandCnt` à une valeur supérieure.


NOTE: L'intervalle de temporisation spécifié est la valeur maximale. Il n'est pas nécessaire d'attendre que le délai maximum soit atteint. La plupart des commandes se terminent dans l'intervalle maximal défini de temps d'attente.

Vous devez également définir le délai maximum pour que SRA effectue une seule opération dans le fichier vvol.properties : offtap.operation.timeout.period.seconds=86400.

https://kb.netapp.com/mgmt/OTV/SRA/NetApp_Storage_Replication_Adapter_4.0%2F%2F7.X_for_ONTAP_Sizing_Guide["Réponse de la base de connaissances NetApp 1001111 : Guide de dimensionnement de NetApp Storage Replication adapter 4.0/7.X pour ONTAP"]

La documentation Broadcom sur la modification des paramètres du fournisseur SAN contient plus d'informations.

https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/site-recovery-manager/8-8/site-recovery-manager-administration-8-8/advanced-srm-configuration/reconfigure-srm-settings/change-storage-settings.html["Modifier les paramètres de stockage"]
