---
permalink: protect/task_enable_storage_replication_adapter.html 
sidebar: sidebar 
keywords:  
summary: 'Les outils ONTAP pour VMware vSphere permettent d"utiliser la fonctionnalité SRA avec VSC pour configurer la reprise après incident.' 
---
= Activez SRA pour protéger les datastores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les outils ONTAP pour VMware vSphere permettent d'utiliser la fonctionnalité SRA avec VSC pour configurer la reprise après incident.

*Ce dont vous aurez besoin*

* Vous devez avoir configuré votre instance vCenter Server et ESXi.
* Vous devez avoir déployé des outils ONTAP.
* Vous devez avoir téléchargé le `.tar.gz` File pour l'appliance SRM uniquement si vous souhaitez configurer la solution de reprise après incident site Recovery Manager (SRM).
+
https://docs.vmware.com/en/Site-Recovery-Manager/8.2/com.vmware.srm.install_config.doc/GUID-B3A49FFF-E3B9-45E3-AD35-093D896596A0.html["Installation et configuration de site Recovery Manager 8.2"] a plus d'informations.



*À propos de cette tâche*

La flexibilité d'activer les fonctionnalités VASA Provider et SRA vous permet d'exécuter uniquement les workflows dont vous avez besoin pour votre entreprise.

*Étapes*

. Connectez-vous à l'interface utilisateur Web de VMware vSphere.
. Depuis le client vSphere, cliquez sur *Menu* > *Console des outils NetApp ONTAP*.
. Cliquez sur *Paramètres*.
. Cliquez sur *gérer les fonctionnalités* dans l'onglet *Paramètres d'administration*.
. Dans la boîte de dialogue *Manage Capabilities*, sélectionnez l'extension SRA à activer.
. Entrez l'adresse IP des outils ONTAP et le mot de passe administrateur, puis cliquez sur *appliquer*.
. Vous pouvez utiliser l'une des méthodes suivantes pour déployer SRA :
+
*Pour l'appareil SRM*

+
.. Accédez à la page de l'appliance SRM, puis à la page Storage Replication Adapters du dispositif SRM.
.. Cliquez sur *Nouvelle carte*.
.. Téléchargez le programme d'installation _.tar.gz_ pour le plug-in SRA sur SRM.
.. Relancez l'analyse des cartes pour vérifier que les détails sont mis à jour dans la page SRM Storage Replication Adapters.




Vous devez vous déconnecter de vSphere client, puis vous reconnecter pour vérifier que l'extension sélectionnée est disponible pour la configuration.

*Informations connexes*

link:../concepts/concept_manage_disaster_recovery_setup_using_srm.html["Configuration de Storage Replication adapter pour la reprise après incident"]
