---
permalink: protect/task_verify_the_replicated_storage_environment.html 
sidebar: sidebar 
keywords:  
summary: 'Vous devez vérifier que le site protégé et le site de reprise sont correctement appariés après la configuration de Storage Replication adapter \(SRA\). Le système de stockage répliqué doit être localisé vers le site protégé et vers le site de reprise.' 
---
= Vérification des systèmes de stockage répliqués
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez vérifier que le site protégé et le site de reprise sont appariés avec succès après la configuration de Storage Replication adapter (SRA). Le système de stockage répliqué doit être localisé vers le site protégé et vers le site de reprise.

*Ce dont vous aurez besoin*

* Vous devez avoir configuré votre système de stockage.
* Vous devez avoir associé le site protégé et le site de reprise à l'aide du gestionnaire de baies SRM.
* Vous devez avoir activé la licence FlexClone et la licence SnapMirror avant d'effectuer l'opération de test de basculement et de basculement pour SRA.


*Étapes*

. Connectez-vous à votre serveur vCenter.
. Accédez à *site Recovery* > *Array Based Replication*.
. Sélectionner la SVM requise, puis vérifier les détails correspondants dans les Array paires.
+
Les systèmes de stockage doivent être découverts sur le site protégé et sur le site de reprise avec l'état « activé ».


