---
permalink: protect/task_configure_folder_mappings.html 
sidebar: sidebar 
keywords:  
summary: Vous devez mapper vos dossiers sur le site protégé et sur le site de restauration pour permettre la communication entre eux. 
---
= Configurer les mappages de dossiers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez mapper vos dossiers sur le site protégé et sur le site de restauration pour permettre la communication entre eux.

*Ce dont vous aurez besoin*

Vous devez avoir connecté les sites protégés et de restauration.

*Étapes*

. Connectez-vous à votre serveur vCenter et cliquez sur *site Recovery* > *sites*.
. Sélectionnez votre site protégé, puis cliquez sur *gérer*.
. Dans l'onglet gérer, sélectionnez *mappages de dossiers*.
. Sélectionnez l'icône *Folder* pour créer un mappage de dossiers.
+
L'assistant de création de mappage de dossier s'affiche.

. Dans l'assistant Créer un mappage de dossier, effectuez les opérations suivantes :
+
.. Sélectionnez *préparer automatiquement les mappages pour les dossiers avec des noms de correspondance*, puis cliquez sur *Suivant*.
.. Sélectionnez les objets de centre de données requis pour les sites protégés et de reprise, puis cliquez sur *Ajouter des mappages*.
.. Cliquez sur *Suivant* une fois les mappages créés.
.. Sélectionnez l'objet utilisé précédemment pour créer un mappage inversé, puis cliquez sur *Terminer*.




*Résultat*

La page mappages des dossiers affiche les ressources du site protégé et les ressources du site de reprise. Vous pouvez suivre les mêmes étapes pour les autres réseaux de votre environnement.
