---
permalink: protect/task_update_sra_credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: 'Pour que SRM communique avec SRA, vous devez mettre à jour les informations d"identification SRA sur le serveur SRM si vous avez modifié les informations d"identification.' 
---
= Mettez à jour les informations d'identification SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour que SRM communique avec SRA, vous devez mettre à jour les informations d'identification SRA sur le serveur SRM si vous avez modifié les informations d'identification.

Vous devez supprimer le dossier de la machine SRM mis en cache ONTAP Tools nom d'utilisateur mot de passe et réinstaller SRA.

*Ce dont vous aurez besoin*

Vous devez avoir exécuté les étapes mentionnées dans la rubrique link:../protect/task_configure_sra_on_srm_appliance.html["Configuration de SRA sur l'appliance SRM"]

*Étapes*

. Exécutez les commandes suivantes pour supprimer le dossier de machine SRM mis en cache Outils ONTAP nom d'utilisateur mot de passe :
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd /conf`
.. `rm -rf *`


. Lancer la commande perl pour configurer SRA avec les nouvelles informations d'identification :
+
.. `cd ..`
.. `perl command.pl -I <otv-IP> administrator <otv-password>`. Vous devez avoir un devis unique autour de la valeur du mot de passe.
+
Un message de confirmation de la mémorisation des identifiants de stockage s'affiche. SRA peut communiquer avec le serveur SRA à l'aide de l'adresse IP, du port et des informations d'identification fournis.




