---
permalink: concepts/concept_configure_high_availability_for_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'Les outils ONTAP prennent en charge une configuration haute disponibilité \(HA\) afin d"assurer la continuité des outils ONTAP en cas de panne.' 
---
= Configuration de la haute disponibilité des outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les outils ONTAP prennent en charge une configuration haute disponibilité afin d'assurer la continuité des outils ONTAP en cas de défaillance.

Les outils ONTAP s'appuient sur la fonction haute disponibilité de VMware vSphere et sur la fonction tolérance aux pannes (FT) de vSphere pour assurer une haute disponibilité. La solution haute disponibilité permet une reprise rapide en cas de panne provoquée par :

* Défaillance d'hôte
* Défaillance du réseau
* Défaillance de machine virtuelle (défaillance du système d'exploitation invité)
* Panne de l'application (outils ONTAP)


Aucune configuration supplémentaire n'est requise pour que les outils ONTAP assurent la haute disponibilité. Seuls les hôtes vCenter Server et ESXi doivent être configurés à l'aide de la fonction HA de VMware vSphere ou de la fonction FT de vSphere en fonction de leurs besoins. La haute disponibilité et la tolérance de défaillance nécessitent des hôtes en cluster associés au stockage partagé. FT a des exigences et des limites supplémentaires.

Outre la solution VMware vSphere HA et la solution vSphere FT, les outils ONTAP pour VMware vSphere permettent également de maintenir les services d'outils ONTAP en permanence. Le processus de surveillance des outils ONTAP surveille régulièrement les trois services et les redémarre automatiquement en cas de défaillance. Ainsi, il est possible d'éviter les défaillances des applications.


NOTE: VCenter HA n'est pas pris en charge par les outils ONTAP.



== Haute disponibilité VMware vSphere

Vous pouvez configurer votre environnement vSphere sur lequel les outils ONTAP pour VMware vSphere sont déployés pour la haute disponibilité (HA). La fonction de haute disponibilité de VMware offre une protection contre les défaillances matérielles et les défaillances du système d'exploitation dans les environnements virtuels.

La fonction VMware HA surveille les machines virtuelles afin de détecter les défaillances du système d'exploitation et du matériel. Lorsqu'une défaillance est détectée, la fonction VMware HA redémarre les machines virtuelles sur les autres serveurs physiques du pool de ressources. Une intervention manuelle n'est pas requise lorsqu'une défaillance de serveur est détectée.

La procédure de configuration de VMware HA dépend de la version de votre serveur vCenter. Par exemple, vous pouvez utiliser le lien de référence suivant et sélectionner la version de vCenter Server requise pour afficher les étapes de configuration de VMware HA.

https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-availability.html["Disponibilité vSphere"]



== Tolérance aux pannes VMware vSphere

La fonction VMware vSphere Fault Tolerance (FT) offre une haute disponibilité (HA) à un niveau plus élevé et permet de protéger les machines virtuelles sans perte de données ni de connexions. Vous devez activer ou désactiver les outils vSphere FT pour ONTAP à partir de votre serveur vCenter.

Assurez-vous que votre licence vSphere prend en charge FT avec le nombre de CPU virtuels requis pour les outils ONTAP dans votre environnement (au moins 2 CPU virtuels ; 4 CPU virtuels pour les environnements à grande échelle).

VSphere FT permet aux machines virtuelles de fonctionner en continu, même en cas de panne de serveur. Lorsque vSphere FT est activé sur une machine virtuelle, une copie de la machine virtuelle principale est automatiquement créée sur un autre hôte (la machine virtuelle secondaire) sélectionné par Distributed Resource Scheduler (DRS). Si DRS n'est pas activé, l'hôte cible est sélectionné à partir des hôtes disponibles. VSphere FT exploite la machine virtuelle principale et la machine virtuelle secondaire en mode parallèle, chaque mise en miroir de l'état d'exécution de la machine virtuelle principale vers la machine virtuelle secondaire.

En cas de défaillance matérielle causant la défaillance de la machine virtuelle principale, la machine virtuelle secondaire reprend immédiatement l'endroit où la machine virtuelle principale est arrêtée. La machine virtuelle secondaire continue de fonctionner sans perte de connexions réseau, de transactions ou de données.

Votre système doit répondre aux exigences du processeur, aux exigences de limite des machines virtuelles et aux exigences de licence pour la configuration de vSphere FT pour votre instance vCenter Server.

La procédure de configuration de HA dépend de la version de votre serveur vCenter. Par exemple, vous pouvez utiliser le lien de référence suivant et sélectionner la version de vCenter Server requise pour afficher les étapes de configuration de HA.

https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/6-5/vsphere-availability.html["Conditions de tolérance aux pannes, limites et licences"]
