---
permalink: concepts/concept_privileges_required_for_vsc_tasks.html 
sidebar: sidebar 
keywords:  
summary: 'Les différents outils ONTAP pour les tâches VMware vSphere nécessitent différentes combinaisons de privilèges spécifiques à Virtual Storage Console \(VSC\) et aux privilèges vCenter Server natifs.' 
---
= Privilèges requis pour les tâches VSC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les différents outils ONTAP pour les tâches VMware vSphere requièrent différentes combinaisons de privilèges spécifiques à Virtual Storage Console (VSC) et vCenter Server natif.

Pour plus d'informations sur les privilèges requis pour les tâches VSC, consultez l'article 1032542 de la base de connaissances NetApp.

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Virtual_Storage_Console_for_VMware_vSphere/How_to_configure_RBAC_for_Virtual_Storage_Console["Comment configurer le RBAC pour Virtual Storage Console"]



== Privilège au niveau du produit requis par les outils ONTAP pour VMware vSphere

Pour accéder aux outils ONTAP pour l'interface utilisateur graphique VMware vSphere, vous devez disposer du privilège de vue spécifique au produit (VSC) attribué au niveau de l'objet vSphere correct. Si vous vous connectez sans ce privilège, VSC affiche un message d'erreur lorsque vous cliquez sur l'icône NetApp et vous empêche d'accéder à VSC.

Dans le privilège *View*, vous pouvez accéder à l'interface utilisateur graphique de VSC. Ce privilège ne vous permet pas d'effectuer des tâches dans VSC. Pour effectuer toutes les tâches VSC, vous devez disposer des privilèges vCenter Server natifs et spécifiques à VSC pour ces tâches.

Le niveau d'affectation détermine les parties de l'interface utilisateur que vous pouvez voir. L'attribution du privilège View (View) à l'objet racine (dossier) vous permet d'entrer dans VSC en cliquant sur l'icône NetApp.

Vous pouvez attribuer le privilège View à un autre niveau d'objets vSphere. Toutefois, vous pouvez limiter les menus VSC que vous pouvez voir et utiliser.

L'objet racine est l'endroit recommandé pour attribuer une autorisation contenant le privilège d'affichage.
