---
permalink: concepts/concept_vmware_high_availability_for_vcenter_server.html 
sidebar: sidebar 
keywords: ONTAP tools 
summary: 'Vous pouvez configurer votre environnement vSphere sur lequel les outils ONTAP pour VMware vSphere sont déployés pour la haute disponibilité \(HA\). La fonction de haute disponibilité de VMware offre une protection contre les défaillances matérielles et les défaillances du système d"exploitation dans les environnements virtuels.' 
---
= Haute disponibilité VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer votre environnement vSphere sur lequel les outils ONTAP pour VMware vSphere sont déployés pour la haute disponibilité (HA). La fonction de haute disponibilité de VMware offre une protection contre les défaillances matérielles et les défaillances du système d'exploitation dans les environnements virtuels.

La fonction VMware HA surveille les machines virtuelles afin de détecter les défaillances du système d'exploitation et du matériel. Lorsqu'une défaillance est détectée, la fonction VMware HA redémarre les machines virtuelles sur les autres serveurs physiques du pool de ressources. Une intervention manuelle n'est pas requise lorsqu'une défaillance de serveur est détectée.

La procédure de configuration de VMware HA dépend de la version de votre serveur vCenter. Par exemple, vous pouvez utiliser le lien de référence suivant et sélectionner la version de vCenter Server requise pour afficher les étapes de configuration de VMware HA.

https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/6-5/vsphere-availability.html["Création et utilisation de clusters HA vSphere"]
