---
permalink: concepts/concept_privileges_required_for_vsc_tasks.html 
sidebar: sidebar 
keywords:  
summary: Différents outils ONTAP pour les tâches VMware vSphere requièrent différentes combinaisons de privilèges spécifiques aux outils ONTAP pour VMware vSphere et aux privilèges vCenter Server natifs. 
---
= Privilèges requis pour les tâches des outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Différents outils ONTAP pour les tâches VMware vSphere requièrent différentes combinaisons de privilèges spécifiques aux outils ONTAP pour VMware vSphere et aux privilèges vCenter Server natifs.

Pour plus d'informations sur les privilèges requis pour les tâches relatives aux outils ONTAP, consultez l'article 1032542 de la base de connaissances NetApp.

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Virtual_Storage_Console_for_VMware_vSphere/How_to_configure_RBAC_for_Virtual_Storage_Console["Comment configurer le RBAC pour Virtual Storage Console"]



== Privilège au niveau du produit requis par les outils ONTAP pour VMware vSphere

Pour accéder à l'interface graphique ONTAP Tools for VMware vSphere, vous devez disposer du privilège de vue spécifique aux outils ONTAP au niveau du produit, attribué au niveau d'objet vSphere approprié. Si vous vous connectez sans ce privilège, ONTAP Tools affiche un message d'erreur lorsque vous cliquez sur l'icône NetApp et vous empêche d'accéder aux outils ONTAP.

Dans le privilège *Afficher*, vous pouvez accéder à l'interface graphique des outils ONTAP. Ce privilège ne vous permet pas d'effectuer des tâches dans les outils ONTAP. Pour effectuer des tâches d'outils ONTAP, vous devez disposer des privilèges vCenter Server natifs et spécifiques aux outils ONTAP pour ces tâches.

Le niveau d'affectation détermine les parties de l'interface utilisateur que vous pouvez voir. L'attribution du privilège d'affichage à l'objet racine (dossier) vous permet d'accéder aux outils ONTAP en cliquant sur l'icône NetApp.

Vous pouvez attribuer le privilège d'affichage à un autre niveau d'objet vSphere. Cependant, cela limite les menus des outils ONTAP que vous pouvez voir et utiliser.

L'objet racine est l'endroit recommandé pour attribuer une autorisation contenant le privilège d'affichage.
