---
permalink: concepts/concept_vcenter_server_role_based_access_control_features_in_vsc_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'VCenter Server assure le contrôle d"accès basé sur des rôles \(RBAC\) qui vous permet de contrôler l"accès aux objets vSphere. Dans les outils ONTAP pour VMware vSphere, vCenter Server RBAC fonctionne avec ONTAP RBAC pour déterminer quelles tâches d"outils ONTAP un utilisateur spécifique peut effectuer sur des objets d"un système de stockage spécifique.' 
---
= Présentation du contrôle d'accès basé sur des rôles dans les outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VCenter Server fournit un contrôle d'accès basé sur des rôles (RBAC) qui vous permet de contrôler l'accès aux objets vSphere. Dans les outils ONTAP® pour VMware vSphere, vCenter Server RBAC fonctionne avec ONTAP RBAC pour déterminer les tâches d'outils ONTAP qu'un utilisateur spécifique peut effectuer sur des objets d'un système de stockage spécifique.

Pour réussir une tâche, vous devez disposer des autorisations appropriées pour le contrôle d'accès basé sur les rôles du serveur vCenter. Au cours d'une tâche, les outils ONTAP vérifient les autorisations du serveur vCenter d'un utilisateur avant de vérifier les privilèges ONTAP de l'utilisateur.

Vous pouvez définir les autorisations de vCenter Server sur l'objet racine (également appelé dossier racine). Vous pouvez ensuite affiner la sécurité en limitant les entités enfants qui n'ont pas besoin de ces autorisations.
