---
permalink: concepts/concept_how_to_configure_data_ontap_role_based_access_control_for_vsc_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'Vous devez configurer le contrôle d"accès ONTAP basé sur des rôles \(RBAC\) sur le système de stockage si vous souhaitez utiliser le contrôle d"accès basé sur des rôles avec les outils ONTAP® pour VMware vSphere. Vous pouvez créer un ou plusieurs comptes utilisateur personnalisés avec des privilèges d"accès limités grâce à la fonction RBAC ONTAP.' 
---
= Configuration du contrôle d'accès basé sur des rôles ONTAP pour les outils ONTAP pour VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez configurer le contrôle d'accès basé sur des rôles (RBAC) ONTAP sur le système de stockage si vous souhaitez utiliser le contrôle d'accès basé sur des rôles avec les outils ONTAP pour VMware vSphere. Vous pouvez créer un ou plusieurs comptes utilisateur personnalisés avec des privilèges d'accès limités grâce à la fonction RBAC ONTAP.

VSC et SRA peuvent accéder aux systèmes de stockage au niveau du cluster ou de la machine virtuelle de stockage (SVM)SVM. Si vous ajoutez des systèmes de stockage au niveau du cluster, vous devez fournir les identifiants de l'utilisateur admin pour fournir toutes les fonctionnalités requises. Si vous ajoutez des systèmes de stockage en ajoutant directement des détails SVM, vous devez savoir que l'utilisateur « vsadmin » n'a pas tous les rôles et les fonctionnalités nécessaires pour effectuer certaines tâches.

Vasa Provider ne peut accéder aux systèmes de stockage qu'au niveau du cluster. Si VASA Provider est requis pour un contrôleur de stockage spécifique, le système de stockage doit être ajouté à VSC au niveau du cluster, même si vous utilisez VSC ou SRA.

Pour créer un nouvel utilisateur et connecter un cluster ou un SVM aux outils ONTAP, il faut effectuer les opérations suivantes :

* Créer un rôle d'administrateur de cluster ou SVM à l'aide de ONTAP System Manager 9.8P1 ou version ultérieure. Voir link:../configure/task_configure_user_role_and_privileges.html["Configurez les rôles et privilèges utilisateur"] pour en savoir plus.
* Créez des utilisateurs avec le rôle attribué et le jeu d'applications approprié à l'aide de ONTAP
+
Ces identifiants sont nécessaires pour configurer les systèmes de stockage pour VSC. Vous pouvez configurer les systèmes de stockage pour VSC en saisissant les identifiants dans VSC. Chaque fois que vous vous connectez à un système de stockage avec ces identifiants, vous disposez d'autorisations pour accéder aux fonctions VSC que vous avez configurées dans ONTAP lors de la création des identifiants.

* Ajoutez le système de stockage à VSC et fournissez les identifiants de l'utilisateur que vous venez de créer




== Rôles VSC

VSC classifie les privilèges ONTAP en fonction de l'ensemble des rôles VSC suivants :

* Détection
+
Permet la détection de tous les contrôleurs de stockage connectés

* Créer un stockage
+
Création de volumes et de LUN

* Modifier le stockage
+
Permet le redimensionnement et la déduplication des systèmes de stockage

* Détruire le stockage
+
Permet la destruction de volumes et de LUN





== Rôles de VASA Provider

Vous pouvez créer uniquement une gestion basée sur des règles au niveau du cluster. Ce rôle permet la gestion du stockage basée sur des règles à l'aide de profils de fonctions de stockage.



== Rôles SRA

SRA classifie les privilèges d'ONTAP en rôle SAN ou NAS au niveau du cluster ou des SVM. Les utilisateurs peuvent ainsi exécuter des opérations SRM.

Lors de l'ajout du cluster à VSC, VSC procède à une validation initiale des rôles RBAC ONTAP. Si vous avez ajouté une adresse IP de stockage SVM directe, VSC n'effectue pas la validation initiale. VSC vérifie et applique les privilèges plus tard dans le flux de travail des tâches.
