---
permalink: concepts/reference_product_level_privilege_required_by_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'Pour accéder aux outils ONTAP® pour l"interface utilisateur graphique VMware vSphere, vous devez disposer du privilège View spécifique au produit (VSC) attribué au niveau de l"objet vSphere correct. Si vous vous connectez sans ce privilège, VSC affiche un message d"erreur lorsque vous cliquez sur l"icône NetApp et vous empêche d"accéder à VSC.' 
---
= Privilège au niveau du produit requis par les outils ONTAP pour VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour accéder aux outils ONTAP® pour l'interface utilisateur graphique VMware vSphere, vous devez disposer du privilège View spécifique au produit (VSC) attribué au niveau de l'objet vSphere correct. Si vous vous connectez sans ce privilège, VSC affiche un message d'erreur lorsque vous cliquez sur l'icône NetApp et vous empêche d'accéder à VSC.

Les informations suivantes décrivent le privilège VSC Product-Level View :

|===


| *Privilège* | *Description* | *Niveau d'affectation* 


 a| 
Afficher
 a| 
Vous pouvez accéder à l'interface graphique de VSC. Ce privilège ne vous permet pas d'effectuer des tâches dans VSC. Pour effectuer toutes les tâches VSC, vous devez disposer des privilèges vCenter Server natifs et spécifiques à VSC pour ces tâches.
 a| 
Le niveau d'affectation détermine les parties de l'interface utilisateur que vous pouvez voir. L'attribution du privilège View (View) à l'objet racine (dossier) vous permet d'entrer dans VSC en cliquant sur l'icône NetApp.

Vous pouvez attribuer le privilège View à un autre niveau d'objets vSphere. Toutefois, vous pouvez limiter les menus VSC que vous pouvez voir et utiliser.

L'objet racine est l'endroit recommandé pour attribuer une autorisation contenant le privilège d'affichage.

|===