---
permalink: concepts/reference_metrocluster_configurations_supported_by_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: Les outils ONTAP pour VMware vSphere prennent en charge les environnements qui utilisent les configurations MetroCluster IP et FC pour ONTAP. La majeure partie de ce support est automatique. Cependant, vous remarquerez peut-être certaines différences lorsque vous utilisez un environnement MetroCluster avec les outils ONTAP et le fournisseur VASA. 
---
= Configurations MetroCluster prises en charge par les outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les outils ONTAP pour VMware vSphere prennent en charge les environnements qui utilisent les configurations MetroCluster IP et FC pour ONTAP. La majeure partie de ce support est automatique. Cependant, vous remarquerez peut-être certaines différences lorsque vous utilisez un environnement MetroCluster avec les outils ONTAP et le fournisseur VASA.



== Configurations MetroCluster et outils ONTAP

Vous devez vous assurer que les outils ONTAP découvrent les contrôleurs du système de stockage sur le site principal et le site secondaire. Généralement, les outils ONTAP découvre automatiquement les contrôleurs de stockage. Si vous utilisez une LIF de gestion de cluster, il est recommandé de vérifier que les outils ONTAP ont détecté les clusters sur les deux sites. Sinon, vous pouvez ajouter manuellement les contrôleurs de stockage aux outils ONTAP. Vous pouvez également modifier les paires de noms d'utilisateur et de mots de passe que les outils ONTAP utilisent pour se connecter aux contrôleurs de stockage.

Lorsqu'un basculement se produit, les SVM sur le site secondaire prennent le contrôle. Ces SVM ont le suffixe «`-mc» ajouté à leurs noms. En cas de basculement lorsque vous effectuez des opérations telles que le provisionnement d'un datastore, le nom de la SVM où réside le datastore est modifié afin d'inclure le suffixe «`-mc ». Ce suffixe est supprimé lorsque le rétablissement se produit, et que les SVM du contrôle de reprise sur le site principal.


NOTE: Si vous avez ajouté des SVM directs avec configuration MetroCluster aux outils ONTAP, après le switchover, la modification du nom du SVM (l'ajout du suffixe «`-mc ») n'est pas reflétée. Toutes les autres opérations de basculement continuent à s'exécuter normalement.

Lors d'un basculement ou d'un rétablissement, la détection et la détection automatiques des clusters peuvent prendre quelques minutes avec les outils ONTAP. Si cela se produit pendant l'exécution d'une opération d'outils ONTAP telle que le provisionnement d'un datastore, vous risquez de rencontrer un retard.



== Configurations MetroCluster et VASA Provider

Vasa Provider prend automatiquement en charge les environnements qui utilisent les configurations MetroCluster. Le basculement est transparent dans les environnements VASA Provider. Vous ne pouvez pas ajouter de SVM directs à VASA Provider.


NOTE: Vasa Provider n'ajoute pas le suffixe «`-mc » aux noms des SVM sur le site secondaire après un basculement.



== Configurations MetroCluster et SRA

Storage Replication adapter (SRA) prend en charge les environnements qui utilisent des configurations MetroCluster (MCC) avec le protocole FC.

Pour les configurations MCC et SRA requises, tous les noms des machines virtuelles de stockage (SVM) doivent être uniques sur les clusters MCC. Si les noms ne sont pas uniques, cela provoque des conflits et les workflows SRA échouent.

Actions requises :

. Après avoir effectué un basculement MCC ou un retour, s'assurer que la commande _snapmirror list-destinations_ sur le cluster source affiche le résultat correct avec le nouveau nom de SVM(<vserver_name>-mc). L'exécution de la commande peut prendre jusqu'à 30 minutes.
. Exécutez l'opération découvreurs à partir de l'interface utilisateur SRM avant de continuer avec d'autres flux de travail SRA. Cette opération permet à SRM de connaître les modifications apportées aux noms des SVM après un switchover ou un switchoback.

