---
permalink: concepts/reference_product_level_privilege_required_by_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'Pour accéder à l"interface graphique ONTAP Tools for VMware vSphere, vous devez disposer du privilège de vue spécifique aux outils ONTAP au niveau du produit, attribué au niveau d"objet vSphere approprié. Si vous vous connectez sans ce privilège, les outils ONTAP affichent un message d"erreur lorsque vous cliquez sur l"icône NetApp et vous empêchent d"accéder aux outils ONTAP.' 
---
= Privilège au niveau du produit requis par les outils ONTAP pour VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour accéder à l'interface utilisateur graphique ONTAP® Tools for VMware vSphere, vous devez disposer du privilège de vue spécifique aux outils ONTAP au niveau du produit, au niveau de l'objet vSphere approprié. Si vous vous connectez sans ce privilège, les outils ONTAP affichent un message d'erreur lorsque vous cliquez sur l'icône NetApp et vous empêchent d'accéder aux outils ONTAP.
Dans le privilège *Afficher*, vous pouvez accéder à l'interface graphique des outils ONTAP. Ce privilège ne vous permet pas d'effectuer des tâches dans les outils ONTAP. Pour effectuer des tâches d'outils ONTAP, vous devez disposer des privilèges vCenter Server natifs et spécifiques aux outils ONTAP pour ces tâches.

Le niveau d'affectation détermine les parties de l'interface utilisateur que vous pouvez voir. L'attribution du privilège d'affichage à l'objet racine (dossier) vous permet d'accéder aux outils ONTAP en cliquant sur l'icône NetApp.

Vous pouvez attribuer le privilège d'affichage à un autre niveau d'objet vSphere. Cependant, cela limite les menus des outils ONTAP que vous pouvez voir et utiliser.

L'objet racine est l'endroit recommandé pour attribuer une autorisation contenant le privilège d'affichage.
