---
permalink: configure/concept_configure_storage_systems_for_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'Vous devez ajouter des systèmes de stockage aux outils ONTAP pour VMware vSphere et définir les informations d"identification par défaut, le cas échéant, à l"aide de l"interface des outils ONTAP.' 
---
= Présentation des systèmes de stockage pour les outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez ajouter des systèmes de stockage aux outils ONTAP pour VMware vSphere et définir les informations d'identification par défaut, le cas échéant, à l'aide de l'interface des outils ONTAP.

Les outils ONTAP pour VMware vSphere offrent un mécanisme unique pour détecter les systèmes de stockage et définir les identifiants de stockage. Les informations d'identification fournissent les autorisations ONTAP requises pour permettre aux utilisateurs des outils ONTAP d'effectuer des tâches à l'aide des systèmes de stockage.

Avant de ONTAP pouvoir afficher et gérer les ressources de stockage, les outils ONTAP doivent détecter les systèmes de stockage. Dans le cadre du processus de détection, vous devez fournir les identifiants ONTAP de vos systèmes de stockage. Il s'agit des privilèges (ou rôles) associés à la paire nom d'utilisateur et mot de passe attribuée à chaque système de stockage. Ces paires de noms d'utilisateur et de mots de passe utilisent le contrôle d'accès basé sur des rôles (RBAC) ONTAP et doivent être configurées depuis ONTAP. Vous ne pouvez pas modifier ces informations d'identification à partir des outils ONTAP. Vous pouvez définir des rôles RBAC ONTAP à l'aide de ONTAP System Manager.


NOTE: Si vous vous connectez en tant qu'administrateur, vous disposez automatiquement de tous les privilèges pour ce système de stockage.

Lorsque vous ajoutez un système de stockage aux outils ONTAP, vous devez fournir une adresse IP pour le système de stockage, ainsi que la paire nom d'utilisateur et mot de passe associée à ce système. Vous pouvez définir les informations d'identification par défaut que les outils ONTAP utiliseront lors du processus de détection du système de stockage ou entrer manuellement les informations d'identification une fois le système détecté. Les détails du système de stockage ajouté aux outils ONTAP pour VMware vSphere sont automatiquement transmis aux extensions que vous activez lors de votre déploiement. Vous n'avez pas besoin d'ajouter manuellement du stockage à VASA Provider et Storage Replication adapter (SRA). Les deux outils ONTAP pour VMware vSphere et SRA prennent en charge l'ajout d'informations d'identification au niveau du cluster et des machines virtuelles de stockage (SVM). Vasa Provider prend uniquement en charge les identifiants au niveau du cluster lors de l'ajout de systèmes de stockage. Lorsque vous ajoutez un système de stockage, toute communication entre le plug-in d'outils ONTAP et le système de stockage doit être authentifiée mutuellement.

Si votre environnement inclut plusieurs instances de serveur vCenter, lorsque vous ajoutez un système de stockage aux outils ONTAP à partir de la page systèmes de stockage, la boîte de dialogue Ajouter un système de stockage affiche une boîte de dialogue serveur vCenter dans laquelle vous pouvez spécifier à quelle instance de serveur vCenter le système de stockage doit être ajouté. Si vous ajoutez un système de stockage en cliquant avec le bouton droit de la souris sur un nom de datacenter, vous n'avez pas la possibilité de spécifier une instance de vCenter Server car le serveur est déjà associé à ce datacenter.

La découverte se fait de l'une des manières suivantes. Dans chaque cas, vous devez fournir des informations d'identification pour tout système de stockage nouvellement découvert.

* Au démarrage du service des outils ONTAP, les outils ONTAP commencent son processus de découverte automatique en arrière-plan.
* Vous pouvez cliquer sur le bouton REDÉCOUVRIR tout dans la page *systèmes de stockage* ou sur un hôte ou un datacenter pour le sélectionner dans le menu *actions* ( *actions* > *outils ONTAP NetApp* > *mettre à jour les données hôte et de stockage* ). Vous pouvez également cliquer sur *DÉCOUVRIR* dans l'onglet *pour commencer* de la section 'Présentation'.


Toutes les fonctions des outils ONTAP nécessitent des autorisations spécifiques pour effectuer des tâches. Vous pouvez limiter ce que les utilisateurs peuvent faire en fonction des informations d'identification associées au rôle ONTAP. Tous les utilisateurs disposant des mêmes nom d'utilisateur et paire de mots de passe du système de stockage partagent le même ensemble d'informations d'identification du système de stockage et peuvent effectuer les mêmes opérations.
