---
permalink: configure/concept_virtual_storage_console_and_vasa_provider_log_files.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez vérifier les fichiers journaux dans le répertoire /opt/netapp/vscserver/log et dans le répertoire /opt/netapp/vpserver/log en cas d"erreur.' 
---
= Fichiers journaux de Virtual Storage Console et de VASA Provider
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez consulter les fichiers journaux dans le répertoire '/opt/netapp/vscserver/log' et dans le répertoire '/opt/netapp/vpserver/log' lorsque vous rencontrez des erreurs.

Les trois fichiers journaux suivants peuvent être utiles pour identifier les problèmes :

* 'cxf.log', contenant des informations sur le trafic API depuis et vers VASA Provider *'kaminoPrefs.xml, contenant des informations sur les paramètres VSC
* 'Vvolvp.log', contenant toutes les informations de journal sur VASA Provider


Le menu de maintenance des outils ONTAP pour VMware vSphere vous permet de définir différents niveaux de journaux en fonction de vos besoins. Les niveaux de journal suivants sont disponibles :

* Info
* Débogage
* Erreur
* Tracé


Lorsque vous définissez les niveaux de journalisation, les fichiers suivants sont mis à jour :

* Serveur VSC : 'kamino.log' et 'vvolvp.log'
* Serveur VASA Provider : 'vvolvp.log', 'error.log' et 'netapp.log'


En outre, la page Web de l'interface de ligne de commandes (CLI) de VASA Provider contient les appels d'API effectués, les erreurs renvoyées et plusieurs compteurs de performances. La page Web CLI se trouve à l'adresse 'https://<IP_address_or_hostname>:9083/stats'[].
