---
permalink: configure/concept_configure_storage_capability_profiles.html 
sidebar: sidebar 
keywords: storage capability profiles 
summary: 'Vasa Provider pour ONTAP vous permet de créer des profils de capacité de stockage et de les mapper sur votre stockage. Cela vous permet de préserver la cohérence dans l"ensemble du stockage. Vous pouvez également utiliser VASA Provider pour vérifier la conformité entre les profils de stockage et de capacité de stockage.' 
---
= Présentation des profils de capacité de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vasa Provider pour ONTAP vous permet de créer des profils de capacité de stockage et de les mapper sur votre stockage. Cela permet d'assurer la cohérence dans l'ensemble du stockage. Vous pouvez également utiliser VASA Provider pour vérifier la conformité entre les profils de stockage et de capacité de stockage.

Une fonctionnalité de stockage est un ensemble d'attributs du système de stockage qui identifie un niveau spécifique de performances de stockage, d'efficacité du stockage et d'autres fonctionnalités telles que le chiffrement de l'objet de stockage associé à la fonctionnalité de stockage.

Pour les datastores traditionnels, vous pouvez utiliser un profil de capacité de stockage pour créer des datastores de manière cohérente avec des attributs communs et leur affecter des règles de QoS. Lors du provisionnement, VSC affiche les clusters, les SVM et les agrégats qui correspondent au profil de fonctionnalité de stockage. Vous pouvez générer un profil de capacité de stockage à partir de datastores traditionnels existants à l'aide de l'option *GLOBAL AUTO-GENERATE PROFILES* du menu mappage du stockage. Une fois le profil créé, vous pouvez utiliser VSC pour contrôler la conformité des datastores avec le profil.


NOTE: Les datastores vVol ne sont pas pris en charge sur les SVM directes.

Lorsqu'il est utilisé avec des datastores vvols, l'assistant de provisionnement peut utiliser plusieurs profils de capacité de stockage pour créer différents volumes FlexVol dans le datastore. Il est possible d'utiliser la stratégie de stockage de VM pour créer automatiquement vvols pour une machine virtuelle dans des volumes FlexVol appropriés tels que définis. Par exemple, vous pouvez créer des profils pour les classes de stockage courantes (par exemple, pour les limites de performance et d'autres fonctionnalités telles que le cryptage ou FabricPool). Vous pouvez par la suite créer des règles de stockage des machines virtuelles dans vCenter Server, qui représentent les classes commerciales des machines virtuelles, et les lier au profil de fonctionnalités de stockage approprié par nom (production, test, RH, par exemple).

Lorsqu'il est utilisé avec vvols, le profil de capacité de stockage est également utilisé pour définir la performance de stockage de l'ordinateur virtuel individuel et le placer sur le volume FlexVol dans le datastore vvols qui répond le mieux aux besoins en termes de performances. Vous pouvez spécifier une règle de QoS avec des IOPS minimales et/ou maximales pour plus de performances. Vous pouvez utiliser les règles par défaut lorsque vous provisionnez une machine virtuelle au départ ou modifier plus tard la règle de stockage de cette machine en cas d'évolution des exigences de l'entreprise. Profils de capacité de stockage par défaut pour cette version des outils ONTAP :

* Aff_Thick
* FAS_MAX20
* FAS_Default
* Aff_Default
* Tiering_AFF
* Aff_chiffré
* Tiering_chiffré_AFF
* Aff_chiffré_Min50
* Platinum
* Bronze


VCenter Server associe ensuite la fonctionnalité de stockage d'une LUN ou d'un volume au datastore provisionné sur cette LUN ou ce volume. Cela vous permet de provisionner une machine virtuelle dans un datastore qui correspond au profil de stockage de la machine virtuelle et de vous assurer que tous les datastores d'un cluster de datastore disposent des mêmes niveaux de service de stockage.

Avec les outils ONTAP, vous pouvez configurer chaque datastore de volume virtuel (vvols) avec un nouveau profil de capacité de stockage qui prend en charge le provisionnement de machines virtuelles avec des besoins en IOPS variables sur le même datastore vvols. Lors de l'exécution du workflow de provisionnement de VM avec un besoin d' IOPS, tous les datastores vvols sont répertoriés dans la liste de datastores compatibles.



== Considérations relatives à la création et à la modification de profils de capacité de stockage

Vous devez tenir compte des considérations relatives à la création et à la modification de profils de capacité de stockage.

* Vous pouvez configurer min IOPS uniquement sur les systèmes AFF.
* Vous pouvez configurer des metrics de qualité de service au niveau d'un datastore de volume virtuel (vvols).
+
Cette fonctionnalité offre une plus grande flexibilité lors de l'affectation de metrics QoS variés pour les différents VMDK de la même machine virtuelle provisionnée dans un datastore virtuel.

* Vous pouvez configurer des profils de capacité de stockage pour les datastores FAS et AFF.
+
Pour les systèmes FAS et AFF, il est possible de configurer la réserve d'espace de manière à ce qu'elle soit fine ou non.

* Vous pouvez utiliser des profils de capacité de stockage pour assurer le cryptage de vos datastores.
* Vous ne pouvez pas modifier des profils de capacité de stockage existants (créés avant la version 7.2) après la mise à niveau d'une version antérieure des outils ONTAP pour VMware vSphere vers la dernière version des outils ONTAP.
+
Les profils de capacité de stockage hérités sont conservés pour une rétrocompatibilité. Si les modèles par défaut ne sont pas utilisés, ils sont remplacés lors de la mise à niveau vers la dernière version des outils ONTAP par les modèles existants qui reflètent les nouvelles mesures de QoS et règles de hiérarchisation liées aux performances des profils de capacités de stockage.

* Vous ne pouvez ni modifier, ni utiliser les profils de capacité de stockage hérités pour provisionner de nouveaux datastores virtuels ni appliquer les règles de stockage de machines virtuelles.
* Vous devez utiliser de nouveaux profils de capacité de stockage pour tous les nouveaux datastores.

