---
permalink: configure/reference_configure_the_vsc_preferences_files.html 
sidebar: sidebar 
keywords: preferences files 
summary: 'Les fichiers de préférences contiennent des paramètres qui contrôlent les outils ONTAP® pour les opérations VMware vSphere. Dans la plupart des cas, il n"est pas nécessaire de modifier les paramètres de ces fichiers. Il est utile de savoir quels fichiers de préférences les outils ONTAP utilisent.' 
---
= Configurez les fichiers de préférences des outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les fichiers de préférences contiennent des paramètres qui contrôlent les outils ONTAP pour les opérations VMware vSphere. Dans la plupart des cas, il n'est pas nécessaire de modifier les paramètres de ces fichiers. Il est utile de savoir quels fichiers de préférences les outils ONTAP utilisent.

Les outils ONTAP contiennent plusieurs fichiers de préférences. Ces fichiers incluent des clés d'entrée et des valeurs qui déterminent comment les outils ONTAP effectuent diverses opérations. Voici quelques-uns des fichiers de préférences utilisés par les outils ONTAP :

`/opt/netapp/vscserver/etc/kamino/kaminoprefs.xml`

`/opt/netapp/vscserver/etc/vsc/vscPreferences.xml`

Vous devrez peut-être modifier les fichiers de préférences dans certaines situations. Par exemple, si vous utilisez iSCSI, NFS ou NVMe/FC et que le sous-réseau est différent entre vos hôtes ESXi et votre système de stockage, vous devez modifier les fichiers de préférences. Si vous ne modifiez pas les paramètres du fichier de préférences, le provisionnement du datastore échoue car les outils ONTAP ne peuvent pas monter le datastore.
