---
permalink: configure/reference_configure_guest_operating_system_scripts.html 
sidebar: sidebar 
keywords: Guest operating system 
summary: 'Les images ISO des scripts \(OS\) du système d"exploitation invité sont montées sur les outils ONTAP® pour le serveur VMware vSphere. Pour utiliser les scripts du système d"exploitation invité afin de définir les délais de stockage des machines virtuelles, vous devez monter les scripts à partir du client vSphere.' 
---
= Configurer les scripts des systèmes d'exploitation invités
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les images ISO des scripts du système d'exploitation invité sont montées sur les outils ONTAP® pour le serveur VMware vSphere. Pour utiliser les scripts du système d'exploitation invité afin de définir les délais de stockage des machines virtuelles, vous devez monter les scripts à partir du client vSphere.

|===


| *Type de système d'exploitation* | *paramètres de temporisation de 60 secondes* | *paramètres de temporisation de 190 secondes* 


 a| 
Linux
 a| 
\https://<appliance_ip>:8143/vsc/public/writable/linux_gos_timeout-install.iso
 a| 
\https://<appliance_ip>:8143/vsc/public/writable/linux_gos_timeout_190-install.iso



 a| 
Répertoires de base
 a| 
\https://<appliance_ip>:8143/vsc/public/writable/windows_gos_timeout.iso
 a| 
\https://<appliance_ip>:8143/vsc/public/writable/windows_gos_timeout_190.iso



 a| 
Solaris
 a| 
\https://<appliance_ip>:8143/vsc/public/writable/solaris_gos_timeout-install.iso
 a| 
\https://<appliance_ip>:8143/vsc/public/writable/solaris_gos_timeout_190-install.iso

|===
Vous devez installer le script à partir de la copie de l'instance VSC enregistrée sur le serveur vCenter (ELM) qui gère la machine virtuelle. Si votre environnement comprend plusieurs serveurs vCenter, vous devez sélectionner l'instance contenant la machine virtuelle pour laquelle vous souhaitez définir les valeurs de délai de stockage.

Vous devez vous connecter à la machine virtuelle, puis exécuter le script pour définir les valeurs de délai de stockage.
