---
permalink: configure/task_regenerate_an_ssl_certificate_for_vsc.html 
sidebar: sidebar 
keywords:  
summary: 'Le certificat SSL est généré lorsque vous installez Virtual Storage Console \(VSC\). Le nom unique \(DN\) généré pour le certificat SSL ne correspond peut-être pas à un nom commun \(CN\) reconnu par les ordinateurs clients. En modifiant les mots de passe du magasin de clés et de la clé privée, vous pouvez régénérer le certificat et créer un certificat spécifique au site.' 
---
= Régénérer un certificat SSL pour Virtual Storage Console
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le certificat SSL est généré lors de l'installation de Virtual Storage Console (VSC). Le nom distinctif (DN) généré pour le certificat SSL peut ne pas être un nom commun (CN) reconnu par les ordinateurs clients. En modifiant les mots de passe du magasin de clés et de la clé privée, vous pouvez régénérer le certificat et créer un certificat spécifique au site.

*À propos de cette tâche*

Vous pouvez activer le diagnostic à distance à l'aide de la console de maintenance et générer un certificat spécifique au site.

https://kb.netapp.com/advice_and_troubleshooting/data_storage_software/vsc_and_vasa_provider/virtual_storage_console%3a_implementing_ca_signed_certificates["Virtual Storage Console : implémentation de certificats signés par une autorité de certification"]

*Étapes*

. Connectez-vous à la console de maintenance.
. Entrez `1` Pour accéder au menu Configuration de l'application.
. Dans le menu Configuration de l'application, entrez `3` Pour arrêter le service VSC.
. Entrez `7` Pour régénérer le certificat SSL.

