---
permalink: configure/task_refresh_the_storage_system_display.html 
sidebar: sidebar 
keywords:  
summary: Vous pouvez utiliser la fonction de mise à jour fournie par les outils ONTAP® pour VMware vSphere pour actualiser les informations sur les systèmes de stockage et forcer les outils ONTAP à détecter les systèmes de stockage. 
---
= Actualiser l'affichage du système de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser la fonction de mise à jour fournie par les outils ONTAP® pour VMware vSphere pour actualiser les informations sur les systèmes de stockage et forcer les outils ONTAP à détecter les systèmes de stockage.

*À propos de cette tâche*

Le `refresh` cette option est utile si vous avez modifié les informations d'identification par défaut des systèmes de stockage après avoir reçu une erreur d'authentification. Vous devez toujours effectuer une opération de mise à jour si vous avez modifié les informations d'identification du système de stockage après que le système de stockage a signalé un `Authentication Failure Status`. Lors de la mise à jour, les outils ONTAP tentent de se connecter au système de stockage en utilisant les nouvelles informations d'identification.

Selon la configuration de votre système, cette tâche peut prendre un certain temps.

*Étapes*

. Sur la page d'accueil du client VMware vSphere, cliquez sur *Storage*.
. Lancer la mise à jour :
+
|===


| *Si cet emplacement est...* | *Cliquez sur...* 


 a| 
Virtual Storage Console
 a| 
L'icône *REDÉCOUVRIR TOUT*.



 a| 
Data Center
 a| 
Cliquez avec le bouton droit de la souris sur le centre de données, puis cliquez sur *NetApp ONTAP Tools* > *Update Host and Storage Data*.

|===
. Dans la boîte de dialogue mettre à jour l'hôte et les données de stockage, cliquez sur *OK*.
+
La détection peut prendre quelques minutes selon le nombre d'hôtes et de systèmes de stockage de votre centre de données. Cette opération de détection fonctionne en arrière-plan.

. Cliquez sur *OK* dans la boîte de dialogue succès.

