---
permalink: configure/task_add_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez ajouter manuellement un système de stockage à Virtual Storage Console \(VSC\).' 
---
= Ajout de systèmes de stockage à VSC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter manuellement un système de stockage à Virtual Storage Console (VSC).

*À propos de cette tâche*

Chaque fois que vous démarrez Virtual Storage Console (VSC) ou que vous sélectionnez l'option *REDÉCOUVREZ tout*, VSC détecte automatiquement les systèmes de stockage disponibles.

*Étapes*

. Ajoutez un système de stockage à VSC en utilisant la page d'accueil des outils ONTAP :
+
** Cliquez sur *Storage Systems* > *Add*.
** Cliquez sur *Présentation* > *pour commencer*, puis sur le bouton *AJOUTER* sous Ajouter un système de stockage.


. Dans la boîte de dialogue *Ajouter un système de stockage*, entrez l'adresse IP de gestion et les informations d'identification pour ce système de stockage.
+
Vous pouvez également ajouter des systèmes de stockage en utilisant l'adresse IPv6 du cluster ou de la SVM. Vous pouvez également modifier les valeurs par défaut pour TLS et le numéro de port dans cette boîte de dialogue.

+
Lorsque vous ajoutez du stockage depuis la page VSC Storage System, vous devez également spécifier l'instance vCenter Server sur laquelle le système de stockage sera situé. La boîte de dialogue Ajouter un système de stockage fournit une liste déroulante des instances de vCenter Server disponibles. VSC n'affiche pas cette option si vous ajoutez du stockage à un data Center déjà associé à une instance de vCenter Server.

. Cliquez sur *OK* après avoir ajouté toutes les informations requises.

