---
permalink: configure/task_discover_storage_systems_and_hosts.html 
sidebar: sidebar 
keywords:  
summary: Lors de la première exécution des outils ONTAP dans un client vSphere, les outils ONTAP permettent de détecter les hôtes ESXi, leurs LUN et leurs exportations NFS, ainsi que les systèmes de stockage NetApp qui possèdent ces LUN et ces exportations. 
---
= Découverte des systèmes et des hôtes de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de la première exécution des outils ONTAP dans un client vSphere, les outils ONTAP permettent de détecter les hôtes ESXi, leurs LUN et leurs exportations NFS, ainsi que les systèmes de stockage NetApp qui possèdent ces LUN et ces exportations.

*Ce dont vous aurez besoin*

* Tous les hôtes ESXi doivent être sous tension et connectés.
* Tous les SVM à découvrir doivent être en cours d'exécution, et chaque nœud de cluster doit disposer d'au moins une LIF de données configurée pour le protocole de stockage utilisé (NFS, iSCSI, FC ou NVMe/FC).


*À propos de cette tâche*

Vous pouvez détecter de nouveaux systèmes de stockage ou mettre à jour les informations concernant les systèmes de stockage existants afin d'obtenir à tout moment les informations les plus récentes sur leur capacité et leur configuration. Vous pouvez également modifier les informations d'identification utilisées par les outils ONTAP pour vous connecter aux systèmes de stockage.

Lors de la découverte des systèmes de stockage, les outils ONTAP collectent des informations à partir des hôtes ESXi gérés par l'instance vCenter Server.

*Étapes*

. Dans la page d'accueil de vSphere client, sélectionnez *hôtes et clusters*.
. Cliquez avec le bouton droit de la souris sur le centre de données requis, puis sélectionnez *NetApp ONTAP Tools* > *Update Host and Storage Data* (mettre à jour les données d'hôte et de stockage*).
+
Les outils ONTAP affichent une boîte de dialogue confirmer qui vous informe que cette action va redémarrer la détection de tous les systèmes de stockage connectés et peut prendre quelques minutes. Voulez-vous continuer ?

. Cliquez sur *OUI*.
. Sélectionnez les contrôleurs de stockage détectés qui sont à l'état `Authentication Failure`, Puis cliquez sur *ACTIONS* > *Modifier*.
. Renseignez les informations requises dans la boîte de dialogue *Modifier le système de stockage*.
. Répétez les étapes 4 et 5 pour tous les contrôleurs de stockage avec `Authentication Failure` état.


Une fois le processus de détection terminé, procédez comme suit :

* Utilisez les outils ONTAP pour configurer les paramètres d'hôte VMware ESXi pour les hôtes qui affichent l'icône alerte dans la colonne Paramètres de l'adaptateur, dans la colonne Paramètres MPIO ou dans la colonne Paramètres NFS.
* Indiquez les informations d'identification du système de stockage.

