---
permalink: configure/task_provision_vvols_datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Vous ne pouvez provisionner un datastore vvols à l"aide de l"assistant de provisionnement de datastore que si VASA Provider est activé dans vos outils ONTAP.' 
---
= Provisionner des datastores vVols
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous ne pouvez provisionner un datastore vvols à l'aide de l'assistant de provisionnement de datastore que si VASA Provider est activé dans vos outils ONTAP.

*Ce dont vous aurez besoin*

* Vous devez vous assurer que les détails de sous-réseau de tous les réseaux auxquels est connecté l'hôte ESXi sont saisis dans le fichier KaminopReFS.xml.
+
Voir la section *activation du montage de datastores sur différents sous-réseaux*.

* Pour que la réplication inverse puisse être correctement effectuée, vous devez configurer des règles et des planifications de réplication similaires sur les datastores des sites source et cible.


Le menu provisionner un datastore vous permet de spécifier un profil de capacité de stockage pour le datastore, ce qui permet de définir des objectifs de niveau de service cohérents et de simplifier le processus de provisionnement. Vous ne pouvez spécifier un profil de capacité de stockage que si vous avez activé VASA Provider.

Les volumes FlexVol utilisés comme stockage de sauvegarde ne sont affichés sur le tableau de bord vvols que s'ils exécutent ONTAP 9.5 ou version ultérieure. Vous ne devez pas utiliser l'assistant de nouveau datastore de vCenter Server pour provisionner les datastores vvols.

* Vous devez utiliser les informations d'identification de cluster pour créer des datastores vVols.
+
Vous ne pouvez pas utiliser les identifiants de SVM pour créer des datastores vVvols.

* Vasa Provider ne prend pas en charge le clonage d'une machine virtuelle hébergée sur le datastore vvols d'un protocole vers un autre datastore avec un protocole différent.
* Vous devez avoir terminé l'association des clusters et des SVM sur les sites source et de destination.


*À propos de cette tâche*


NOTE: La version 9.10 des outils ONTAP prend en charge la création de datastores vvols avec une taille vmdk supérieure à 16 To pour toutes les baies SAN (ASA) de type ONTAP 9.9.1 ou version ultérieure.

*Étapes*

. Dans la page d'accueil de vSphere client, cliquez sur *hôtes et clusters*.
. Dans le volet de navigation, sélectionnez le datacenter sur lequel vous souhaitez provisionner le datastore.
. Spécifiez les hôtes sur lesquels vous souhaitez monter le datastore.
+
|===


| *Pour rendre le datastore disponible à...* | *Faites cela...* 


 a| 
Tous les hôtes d'un data Center
 a| 
Cliquez avec le bouton droit de la souris sur un data Center, puis sélectionnez *NetApp ONTAP Tools* > *Provision datastore*.



 a| 
Tous les hôtes d'un cluster
 a| 
Cliquez avec le bouton droit de la souris sur un cluster, puis sélectionnez *Outils ONTAP NetApp* > *Provision datastore*.



 a| 
Un hôte unique
 a| 
Cliquez avec le bouton droit de la souris sur un hôte, puis sélectionnez *Outils ONTAP NetApp* > *Provision datastore*.

|===
. Renseignez les champs de la boîte de dialogue Nouveau datastore pour créer le datastore.
+
La plupart des champs de la boîte de dialogue sont explicites. Le tableau suivant décrit certains des champs pour lesquels vous pouvez avoir besoin de conseils.

+
|===


| *Section* | *Description* 


 a| 
Généralités
 a| 
La section général de la boîte de dialogue Nouveau datastore propose des options permettant de saisir l'emplacement, le nom, la description, le type et le protocole du nouveau datastore. Le type de datastore vVvols est utilisé pour configurer un datastore vVvols.

Vous pouvez provisionner le datastore vVols si la fonctionnalité du fournisseur VASA est activée. Voir, link:../deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html["Activez VASA Provider pour la configuration des datastores virtuels"] pour plus d'informations. Le datastore vVols prend en charge les protocoles NFS, iSCSI, FC/FEoE et NVMe/FC.


NOTE: Le protocole NVMe/FC pour le datastore vVols est disponible si les outils ONTAP sont enregistrés dans vCenter 8.0 et versions ultérieures, et si la version ONTAP est ONTAP 9.91P3 et versions ultérieures.


NOTE: Si vous provisionnez un datastore iSCSI vvols pour la réplication vvols, avant de créer un datastore vvols sur le site cible, vous devez procéder à une mise à jour SnapMirror et à une redécouverte de clusters.



 a| 
Adieu les migrations de données onéreuses
 a| 
Cette section vous permet de choisir si vous souhaitez que la réplication soit activée ou désactivée pour le datastore vVvols. Seul le profil de réplication de type asynchrone est autorisé pour cette version. Vous pouvez ensuite sélectionner un ou plusieurs profils de capacité de stockage répertoriés. Les valeurs recommandées par le système pour *Storage system* et *Storage VM* associés sont remplies automatiquement. Les valeurs recommandées sont renseignées uniquement si elles sont appariées dans ONTAP. Vous pouvez modifier ces valeurs si nécessaire.

*Remarque :* lors de la création de volumes FlexVol dans ONTAP, veillez à les créer avec les attributs que vous souhaitez sélectionner dans le profil de capacité de stockage. Les volumes FlexVol de lecture/écriture et de protection des données doivent avoir des attributs similaires.

Une fois les volumes FlexVol créés et l'initialisation de SnapMirror dans ONTAP, vous devez exécuter une redécouverte de stockage dans les outils ONTAP pour pouvoir voir les nouveaux volumes.



 a| 
Les attributs de stockage
 a| 
Dans la liste existante, vous devez sélectionner la planification de SnapMirror et le volume FlexVol requis. Cette planification doit être similaire à celle sélectionnée sur la page VM Storage Policies. L'utilisateur doit avoir créé des volumes FlexVol sur ONTAP avec SnapMirror qui sont répertoriés. Vous pouvez sélectionner le profil de capacité de stockage par défaut à utiliser pour la création de vVols à l'aide de l'option *profil de capacité de stockage par défaut*. Par défaut, tous les volumes sont définis sur la taille de croissance automatique maximale sur 120 % et les snapshots par défaut sont activés sur ces volumes.

*Remarque :*

** Un volume FlexVol qui fait partie d'un datastore vVols ne peut pas diminuer la taille existante mais peut croître de 120 % au maximum. Les snapshots par défaut sont activés sur ce volume FlexVol.
** La taille minimale d'un volume FlexVol que vous devez créer est de 5 Go.


|===
. Dans la section Résumé, cliquez sur *Terminer*.


*Résultat*

Un groupe de réplication est créé en back-end lorsqu'un datastore vVvols est configuré.

*Informations connexes*

link:../manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html["Analysez les données de performance à l'aide du tableau de bord vvols"]
