---
permalink: configure/task_create_storage_capability_profiles.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez utiliser les outils ONTAP pour créer manuellement des profils de capacité de stockage, générer automatiquement un profil basé sur les fonctionnalités d"un datastore ou modifier un profil pour répondre à vos besoins.' 
---
= Créer des profils de capacité de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser les outils ONTAP pour créer manuellement des profils de capacité de stockage, générer automatiquement un profil basé sur les fonctionnalités d'un datastore ou modifier un profil pour répondre à vos besoins.

*Ce dont vous aurez besoin*

Vous devez avoir enregistré votre instance VASA Provider avec les outils ONTAP pour VMware vSphere.

Après avoir configuré un profil, vous pouvez le modifier si nécessaire.

*Étapes*

. Sur la page d'accueil des outils ONTAP, cliquez sur *stratégies et profils*.
. Créez un profil ou modifiez un profil existant, selon les besoins :
+
|===


| *Si vous voulez...* | *Faites cela...* 


 a| 
Créer un profil
 a| 
Cliquez sur *CRÉER*.



 a| 
Modifier un profil existant
 a| 
Cliquez sur le profil que vous souhaitez modifier dans les profils répertoriés sur la page *profils de capacité de stockage*.

|===
+

NOTE: Pour afficher les valeurs associées à un profil existant, vous pouvez cliquer sur le nom du profil dans la page profil de capacités de stockage. Vasa Provider affiche alors la page Résumé de ce profil.

. Dans *Nouveau datastore* > *systèmes de stockage*, cliquez sur *Créer un profil de capacité de stockage*.
+
Vous obtenez le message suivant pour confirmer la navigation loin de la fenêtre datastore.

+
_Ceci supprimera les données saisies en fermant le flux de travail actuel et ouvre le flux de travail Créer un profil de capacité de stockage. Voulez-vous continuer?_

. Cliquez sur *YES* pour ouvrir la fenêtre Créer un profil de capacité de stockage.
. Complétez les pages de l'assistant Créer un profil de capacité de stockage pour configurer un profil ou modifier des valeurs pour modifier un profil existant.
+
La plupart des champs de cet assistant sont explicites. Le tableau suivant décrit certains des champs pour lesquels vous pouvez avoir besoin de conseils.

+
|===


| *Champ* | *Explication* 


 a| 
Identification de plusieurs profils
 a| 
Vous pouvez utiliser le champ *Description* de l'onglet Nom et Description pour décrire l'objectif du profil de capacité de stockage (SCP). Fournir une bonne description est utile car il est conseillé de configurer différents profils en fonction des applications utilisées.

Par exemple, une application stratégique nécessite un profil offrant des fonctionnalités capables de prendre en charge des performances plus élevées, comme la plateforme AFF et ASA. Un datastore utilisé à des fins de test ou de formation peut utiliser un profil doté d'une plateforme hybride pour baie Flash aux performances moins élevées, et permettre à toutes les fonctionnalités d'efficacité du stockage et à la hiérarchisation de contrôler les coûts.
La combinaison du type de plate-forme et de l'indicateur asymétrique détermine le type de SCP. Par exemple : Platinum_ASA_A, Platinum_AFF_A, Platinum_AFF_C.

Si vous avez activé le mode « lié » pour vos serveurs vCenter, vous devez sélectionner le serveur vCenter pour lequel vous créez le profil de capacité de stockage.



 a| 
Plateforme
 a| 
Vous pouvez créer un profil de capacité de stockage avec les types de plateforme : performance, capacité, baie Flash hybride et une nouvelle fonctionnalité de stockage avec indicateur asymétrique. Les options des écrans suivants sont mises à jour en fonction de votre sélection de type de système de stockage.



 a| 
Protocole
 a| 
Vous pouvez faire votre choix parmi les protocoles disponibles répertoriés en fonction de la plateforme sélectionnée pour le système de stockage. Lors de la configuration de machines virtuelles, vous pouvez configurer des stratégies de stockage de machines virtuelles avec un profil de capacité de stockage et le champ de protocole filtre les datastores en fonction de protocoles spécifiques. Le champ « tous » vous permet de travailler avec tous les protocoles.



 a| 
Performance
 a| 
Vous pouvez définir des règles QoS classiques pour votre système de stockage à l'aide de l'onglet performances.

** Lorsque vous sélectionnez *aucun*, une règle de QoS sans limite (infinie) est appliquée à un VVol de données.
** Lorsque vous sélectionnez *QoS Policy Group*, une règle de QoS classique s'applique à un VVol.
+
Vous pouvez définir la valeur pour *Max IOPS* et *min IOPS* qui vous permet d'utiliser la fonctionnalité QoS. Si vous sélectionnez Infinite IOPS, le champ Max IOPS est désactivé. Lorsqu'elle est appliquée à un datastore traditionnel, une politique de QoS avec la valeur « Max IOPS » est créée et attribuée à un volume FlexVol. Lorsqu'il est utilisé dans un datastore vvols, une stratégie de qualité de services avec des valeurs Max IOPS et min IOPS est créée pour chaque datastore vvols.

+
*REMARQUE* :

+
*** Des IOPS maximales et un nombre d'IOPS minimum peuvent également être appliqués au volume FlexVol pour un datastore classique.
*** Vous devez vérifier que les metrics de performance ne sont pas définis séparément au niveau des machines virtuelles de stockage, de l'agrégat ou du volume FlexVol.






 a| 
Attributs de stockage
 a| 
Les attributs de stockage que vous pouvez activer dans cet onglet dépendent du type de stockage que vous sélectionnez dans l'onglet personnalité.

** Si vous sélectionnez un système de stockage hybride avec baie Flash, vous pouvez configurer la réserve d'espace (Thick ou Thin), activer la déduplication, la compression et le chiffrement.
+
L'attribut de hiérarchisation est désactivé car cet attribut ne s'applique pas au stockage hybride de la baie Flash.

** Si vous sélectionnez le stockage AFF, vous pouvez activer le cryptage et le Tiering.
+
La déduplication et la compression sont activées par défaut pour le stockage AFF et ne peuvent pas être désactivées.

** Si vous sélectionnez le stockage ASA, vous pouvez activer le chiffrement et la hiérarchisation.
+
La déduplication et la compression sont activées par défaut pour le stockage ASA et ne peuvent pas être désactivées.

+
L'attribut de Tiering permet d'utiliser les volumes faisant partie d'un agrégat compatible FabricPool (pris en charge par VASA Provider pour les systèmes AFF avec ONTAP 9.4 et versions ultérieures). Vous pouvez configurer l'une des règles suivantes pour l'attribut de hiérarchisation :

** Aucune : empêche le déplacement des données de volume vers le niveau de capacité
** Snapshot : déplace les blocs de données utilisateur des copies Snapshot de volumes qui ne sont pas associées au système de fichiers actif vers le Tier de capacité


|===
. Vérifiez vos sélections sur la page Résumé, puis cliquez sur *OK*.
+
Après avoir créé un profil, vous pouvez revenir à la page mappage du stockage pour afficher les profils correspondant aux datastores.


