---
permalink: manage/concept_datastore_reports.html 
sidebar: sidebar 
keywords: Datastore Reports 
summary: Les rapports datastore fournissent des informations détaillées sur les datastores traditionnels et les machines virtuelles créées sur ces datastores. 
---
= Rapports sur les datastores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les rapports datastore fournissent des informations détaillées sur les datastores traditionnels et les machines virtuelles créées sur ces datastores.

Le tableau de bord traditionnel vous permet d'examiner et d'identifier les problèmes potentiels avec les datastores et les machines virtuelles de votre serveur vCenter. Vous pouvez afficher, trier et exporter des rapports. Le rapport sur les données des datastores traditionnels et des machines virtuelles est fourni par vCenter Server. Toutefois, ONTAP a fourni des mesures telles que la latence, le débit et les IOPS, grâce à l'introduction de la prise en charge des datastores pris en charge par les data stores pris en charge par FlexGroup.


NOTE: Le contrôle des fichiers n'est pas pris en charge pour les datastores FlexGroup configurés sur des SVM (Direct Storage Virtual machines).

Le datastore fournit les rapports prédéfinis suivants :

* Rapport datastore
* Rapport de machine virtuelle


*Rapport datastore*

+ le menu Rapport datastore fournit des informations sur les paramètres suivants pour les datastores :

* Nom du datastore
* Type de datastore : NFS ou VMFS
* Style de volume
+
Le style de volume peut être un volume FlexVol ou FlexGroup.

* Espace libre
* Espace utilisé
* Espace total
* Pourcentage d'espace utilisé
* Pourcentage d'espace disponible
* D'IOPS
+
Le rapport affiche les opérations d'E/S par seconde du datastore.

* Latence
+
Le rapport affiche les informations de latence pour le datastore.

+
Vous pouvez également vérifier l'heure à laquelle le rapport a été généré. Le menu Rapport datastore vous permet d'organiser le rapport selon vos besoins, puis d'exporter le rapport organisé à l'aide du bouton *Exporter vers CSV*. Les noms de datastores du rapport sont des liens qui se trouvent dans l'onglet Monitor du datastore sélectionné, dans lequel vous pouvez afficher les mesures de performances du datastore.



*Rapport de machine virtuelle*

+ le menu Rapport de la machine virtuelle fournit les mesures de performances pour toutes les machines virtuelles qui utilisent des datastores provisionnés par VSC pour un serveur vCenter sélectionné. Les indicateurs de machine virtuelle affichés dans les rapports de machine virtuelle sont des données historiques collectées toutes les 30 minutes pour les machines virtuelles sur des datastores traditionnels. Les « temps de dernière actualisation » et « temps de réactualisation suivant » sont ajoutés au tableau pour fournir des détails sur la date de collecte des données et quand sera la prochaine collecte de données.

* Nom de la machine virtuelle
* Nom du datastore
* Style de volume
+
Le style de volume peut être un volume FlexVol ou FlexGroup.

* Source
+
La source permettant de collecter des détails sur la machine virtuelle peut être ONTAP ou vCenter Server.

* Latence
+
Le rapport affiche la latence des machines virtuelles sur tous les datastores associés aux machines virtuelles.

* D'IOPS
* Débit
* De la capacité
+
Le rapport affiche la valeur de la capacité engagée pour une machine virtuelle.

* Hôte
+
Le rapport affiche les systèmes hôtes sur lesquels la machine virtuelle est disponible.

* Continuité
+
Le rapport indique l'heure à laquelle la machine virtuelle est mise sous tension et disponible sur un hôte ESXi.

* État de l'alimentation
+
Le rapport indique si la machine virtuelle est sous tension ou hors tension.



Chaque nom de machine virtuelle dans le rapport est un lien vers l'onglet Monitor de la machine virtuelle sélectionnée. Vous pouvez trier le rapport de la machine virtuelle selon vos besoins et exporter le rapport dans un fichier .CSV, puis enregistrer le rapport sur votre système local. L'horodatage du rapport est également ajouté au rapport enregistré.

Pour les machines virtuelles qui sont sauvegardées par des volumes FlexGroup, lorsque la nouvelle machine virtuelle est mise sous tension, les fichiers sont enregistrés pour surveillance sur ONTAP. Les mesures historiques de latence, de débit et d'IOPS sont obtenues lors de l'accès aux rapports des machines virtuelles à partir de ONTAP.
