---
permalink: manage/concept_what_vasa_provider_reports_do.html 
sidebar: sidebar 
keywords: VSC, VASA Provider, and SRA 
summary: 'Les rapports vVvols affichent des informations détaillées sur les datastores VMware Virtual volumes \(vVvols\) et les machines virtuelles qui sont créées sur ces datastores. Le tableau de bord vVvols vous permet d"examiner et d"identifier les problèmes potentiels avec les datastores vvols et les machines virtuelles de votre serveur vCenter.' 
---
= Rapports vVols
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les rapports vvols affichent des informations détaillées sur les datastores VMware Virtual volumes (vvols) et les machines virtuelles qui sont créées sur ces datastores. Le tableau de bord vVvols vous permet d'examiner et d'identifier les problèmes potentiels avec les datastores vvols et les machines virtuelles de votre serveur vCenter.

Vous pouvez afficher, organiser et exporter des rapports. Les données pour les datastores vvols et les machines virtuelles sont fournies par ONTAP avec OnCommand API Services.

VVvols fournit les rapports prédéfinis suivants :

* Rapport de datastore vVvols
* Rapport VM vVvols


*VVvols datastore Report*

+ le menu de rapport de datastore vvols fournit des informations sur les paramètres suivants pour les datastores :

* Nom du datastore vVols
* Espace libre
* Espace utilisé
* Espace total
* Pourcentage d'espace utilisé
* Pourcentage d'espace disponible
* D'IOPS
* Les metrics de performance de latence sont disponibles pour les datastores NFS basés sur ONTAP 9.8 et versions ultérieures. Vous pouvez également vérifier l'heure à laquelle le rapport a été généré. Le menu de rapport de datastore vVvols vous permet d'organiser le rapport selon vos besoins, puis d'exporter le rapport organisé à l'aide du bouton *Exporter vers CSV*. Chaque nom de datastore SAN vVols du rapport est un lien qui navigue vers l'onglet Monitor du datastore SAN vVvols sélectionné, que vous pouvez utiliser pour afficher les metrics de performances.


*VVvols Virtual machine Report*

+ le menu de rapport de synthèse de machine virtuelle vvols fournit les indicateurs de performance de toutes les machines virtuelles qui utilisent les datastores SAN vvols qui sont provisionnés par VASA Provider pour ONTAP pour un serveur vCenter sélectionné. Les indicateurs de machine virtuelle affichés dans les rapports VM sont des données historiques collectées toutes les 10 minutes pour les machines virtuelles sur les datastores vVvols. « Heure de dernière actualisation » et « prochaine actualisation » sont ajoutés au tableau pour fournir des informations sur la date de collecte des données et quand sera la prochaine collecte de données.

* Nom de la machine virtuelle
* De la capacité
* Continuité
* D'IOPS
* Débit
+
Le rapport indique si la machine virtuelle est sous tension ou hors tension.

* Espace logique
* Hôte
* État de l'alimentation
* Latence
+
Le rapport affiche la latence des machines virtuelles sur tous les datastores vvols qui sont associés aux machines virtuelles.



Chaque nom de machine virtuelle dans le rapport est un lien vers l'onglet Monitor de la machine virtuelle sélectionnée. Vous pouvez organiser le rapport de la machine virtuelle selon vos besoins, exporter le rapport au format .CSV, puis enregistrer le rapport sur votre système local. L'horodatage du rapport est ajouté au rapport enregistré.
