---
permalink: manage/reference_verify_vvols_dashboard_data_requirements.html 
sidebar: sidebar 
keywords: vVol dashboard 
summary: 'Vous devez vérifier certaines exigences importantes du tableau de bord vVvols pour afficher les détails dynamiques des datastores VMware Virtual volumes \(vvols\) et des machines virtuelles.' 
---
= Exigences de données de tableau de bord de vVvols
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez vérifier certaines exigences importantes du tableau de bord vVvols pour afficher les détails dynamiques des datastores VMware Virtual volumes (vvols) et des machines virtuelles.

Le tableau suivant présente un aperçu de ce que vous devez vérifier si le tableau de bord vvols n'affiche pas les indicateurs de performances pour les datastores SAN vvols et les machines virtuelles provisionnés.

|===
| *Considérations* | *Description* 


 a| 
Adieu les migrations de données onéreuses
 a| 
* Vous utilisez ONTAP 9.7 ou une version ultérieure.
* Vous utilisez les identifiants appropriés pour le système de stockage.
* Votre système de stockage est actif et accessible.
* La machine virtuelle que vous avez sélectionnée doit utiliser au moins un datastore vvols et les opérations d'E/S s'exécutent sur le disque de la machine virtuelle.


|===