---
permalink: manage/task_mount_a_vvols_datastore.html 
sidebar: sidebar 
keywords: Mount vVol 
summary: 'Vous pouvez monter un datastore VMware Virtual volumes \(vVvols\) sur un ou plusieurs hôtes supplémentaires en utilisant la boîte de dialogue Mount vvols datastore. Le montage du datastore permet d"accéder au stockage à des hôtes supplémentaires.' 
---
= Montez un datastore vvols
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez monter un datastore VMware Virtual volumes (vvols) sur un ou plusieurs hôtes supplémentaires en utilisant la boîte de dialogue Mount vvols datastore. Le montage du datastore permet d'accéder au stockage à des hôtes supplémentaires.

*Étapes*

. Dans la page d'accueil de vSphere client, cliquez sur *hôtes et clusters*.
. Cliquez avec le bouton droit de la souris sur le datastore à monter, puis sélectionnez *NetApp ONTAP Tools* > *Mount vvols datastore*.
+
La boîte de dialogue Mount vvols datastore s'affiche, qui fournit une liste des hôtes disponibles dans le centre de données où vous pouvez monter le datastore. La liste ne comprend pas les hôtes sur lesquels le datastore a déjà été monté, les hôtes qui exécutent ESX 5.x ou version antérieure, ou les hôtes qui ne prennent pas en charge le protocole de datastore. Par exemple, si un hôte ne prend pas en charge le protocole FC, vous ne pouvez pas monter un datastore FC sur l'hôte.

+

IMPORTANT: Même si vSphere client fournit une boîte de dialogue de montage pour vCenter Server, vous devez toujours utiliser la boîte de dialogue VASA Provider pour cette opération. Vasa Provider configure l'accès aux systèmes de stockage exécutant le logiciel ONTAP.

. Sélectionnez l'hôte sur lequel vous souhaitez monter le datastore, puis cliquez sur *OK*.

