---
permalink: manage/task_collect_the_log_files.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez collecter les fichiers journaux des outils ONTAP® pour VMware vSphere à partir de l"option disponible dans l"interface graphique \(GUI\) de VSC. Le support technique peut vous demander de collecter les fichiers journaux afin de résoudre un problème.' 
---
= Collectez les fichiers journaux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez collecter les fichiers journaux des outils ONTAP pour VMware vSphere à partir de l'option disponible dans l'interface graphique de VSC. Le support technique peut vous demander de collecter les fichiers journaux afin de résoudre un problème.

*À propos de cette tâche*

Si vous avez besoin de fichiers journaux de VASA Provider, vous pouvez générer un bundle de support à partir de l'écran du panneau de configuration du fournisseur. Cette page fait partie des menus de maintenance de VASA Provider, accessibles depuis la console de l'appliance virtuelle.

`\https://vm_ip:9083`

Vous pouvez collecter les outils ONTAP pour les fichiers journaux VMware vSphere à l'aide de la fonctionnalité « Exporter les outils ONTAP pour les journaux VMware vSphere » de l'interface utilisateur graphique de VSC. Lorsque vous collectez un bundle ONTAP Tools pour VMware vSphere Log avec VASA Provider activé, le bundle ONTAP Tools pour VMware vSphere Log contient également les journaux VP. Les étapes suivantes expliquent comment collecter les outils ONTAP pour les fichiers journaux VMware vSphere :

*Étapes*

. Sur la page d'accueil des outils ONTAP, cliquez sur *Configuration* > *Exporter les outils ONTAP pour les journaux VMware vSphere*.
+
Cette opération peut prendre plusieurs minutes.

. Lorsque vous y êtes invité, enregistrez le fichier sur votre ordinateur local.
+
Vous pouvez ensuite envoyer le fichier _.zip_ au support technique.


