---
permalink: manage/task_check_for_datastore_compliance_with_the_mapped_storage_capability_profile.html 
sidebar: sidebar 
keywords:  
summary: Vous pouvez rapidement vérifier si vos datastores sont conformes avec les profils de capacité de stockage mappés aux datastores. 
---
= Vérifiez la conformité du datastore avec le profil de capacité de stockage mappé
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez rapidement vérifier si vos datastores sont conformes avec les profils de capacité de stockage mappés aux datastores.

*Ce dont vous aurez besoin*

* Vous devez avoir enregistré votre instance VASA Provider à l'aide des outils ONTAP® pour VMware vSphere (VSC).
* VSC doit avoir découvert votre système de stockage.


*Étapes*

. Dans la page d'accueil des outils ONTAP, cliquez sur *mappage de stockage*.
. Consultez les informations de la colonne Statut de conformité pour identifier les datastores non conformes et examinez les alertes pour des raisons de non-conformité.
+

NOTE: Lorsque vous cliquez sur le bouton *COMPLIANCE CHECK*, VSC effectue une nouvelle détection pour l'ensemble du stockage, ce qui peut prendre quelques minutes.

+
Si un datastore n'est plus conforme à son profil, la colonne État de conformité affiche une alerte indiquant la raison de la non-conformité. Par exemple, un profil peut nécessiter une compression. Si ce paramètre a été modifié sur le stockage, la compression n'est plus utilisée et le datastore n'est pas compatible.



Lorsque vous découvrez un datastore qui n'est pas compatible avec son profil, vous pouvez modifier les paramètres du volume qui soutient le datastore pour le rendre compatible ou vous pouvez attribuer un nouveau profil au datastore.

Vous pouvez modifier les paramètres à partir de la page profil de capacité de stockage.
