---
permalink: manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez surveiller les performances et afficher les cinq principaux datastores SAN et NAS VMware Virtual volumes \(vvols\) dans votre vCenter Server en fonction des paramètres que vous sélectionnez à l"aide du tableau de bord vvols des outils ONTAP.' 
---
= Analysez les données de performance à l'aide du tableau de bord vvols
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez surveiller les performances et afficher les cinq principaux datastores SAN et NAS VMware Virtual volumes (vvols) dans votre vCenter Server en fonction des paramètres que vous sélectionnez à l'aide du tableau de bord vvols des outils ONTAP.

*Ce dont vous aurez besoin*

* Vous devez utiliser ONTAP 9.7 ou une version ultérieure pour votre système de stockage.


Les données IOPS fournies par ONTAP sont arrondies et affichées sur le tableau de bord vvols. Il peut y avoir une différence entre la valeur IOPS réelle fournie par ONTAP et la valeur IOPS affichée sur le tableau de bord vvols. Les outils ONTAP permettent de surveiller les performances des datastores vvols basés sur NFS.

* Les données du tableau de bord vvols sont régulièrement actualisées, à un intervalle de 10 minutes.
* Si vous avez ajouté, modifié ou supprimé un système de stockage de votre instance vCenter Server, vous ne remarquerez peut-être pas de changement dans les données du tableau de bord vvols pendant un certain temps.
* La valeur d'IOPS totale affichée dans le portlet vue d'ensemble du tableau de bord vVols n'est pas une valeur cumulée de la valeur d'IOPS de lecture et d'écriture.
* Les données NFS vVvols provisionnés sur ONTAP 9.8 et versions ultérieures sont automatiquement enregistrés pour la surveillance des performances dans le tableau de bord vvols.


*Étapes*

. Dans la page d'accueil de vSphere client, cliquez sur *ONTAP Tools*.
. Sélectionnez le serveur vCenter requis à l'aide du sélecteur *INSTANCE* pour afficher les datastores.
. Cliquez sur *Présentation > vVols Dashboard*.
+
Le portlet datastores fournit les informations suivantes :

+
** Nombre de datastores vvols gérés par VASA Provider dans votre instance vCenter Server
** Les cinq principaux datastores vvols d'après l'utilisation des ressources et les paramètres de performance, vous pouvez modifier la liste des datastores en fonction de l'espace utilisé, d'IOPS, ou de latence, et dans l'ordre requis.


. Affichez les détails des machines virtuelles à l'aide du portlet machines virtuelles.
+
Le portlet machines virtuelles fournit les informations suivantes :

+
** Nombre de machines virtuelles utilisant des datastores ONTAP dans votre serveur vCenter
** Les cinq meilleures machines virtuelles basées sur les IOPS, la latence, le débit, la capacité engagée, la disponibilité Et espace logique vous pouvez personnaliser la manière dont les cinq principales machines virtuelles sont répertoriées dans le tableau de bord vVvols.






== Exigences de données de tableau de bord de vVvols

Vous devez vérifier certaines exigences importantes du tableau de bord vVvols pour afficher les détails dynamiques des datastores VMware Virtual volumes (vvols) et des machines virtuelles.

Le tableau suivant présente un aperçu de ce que vous devez vérifier si le tableau de bord vvols n'affiche pas les indicateurs de performances pour les datastores SAN vvols et les machines virtuelles provisionnés.

|===
| *Considérations* | *Description* 


 a| 
Adieu les migrations de données onéreuses
 a| 
* Vous utilisez ONTAP 9.7 ou une version ultérieure.
* Vous utilisez les identifiants appropriés pour le système de stockage.
* Votre système de stockage est actif et accessible.
* La machine virtuelle que vous avez sélectionnée doit utiliser au moins un datastore vvols et les opérations d'E/S s'exécutent sur le disque de la machine virtuelle.


|===