---
permalink: manage/task_set_default_credentials_for_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez utiliser les outils ONTAP® pour VMware vSphere pour définir les informations d"identification par défaut d"un système de stockage dans votre serveur vCenter.' 
---
= Définissez les identifiants par défaut des systèmes de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser les outils ONTAP pour VMware vSphere pour définir les informations d'identification par défaut d'un système de stockage sur votre serveur vCenter.

*Ce dont vous aurez besoin*

Vous devez avoir sélectionné le serveur vCenter que vous souhaitez utiliser pour créer des informations d'identification par défaut.

*À propos de cette tâche*

Si vous configurez des identifiants par défaut pour les systèmes de stockage, Virtual Storage Console (VSC) utilise ces identifiants pour vous connecter à un système de stockage que VSC vient de découvrir. Si les informations d'identification par défaut ne fonctionnent pas, vous devez vous connecter manuellement au système de stockage. Prise en charge de VSC et SRA via l'ajout des informations d'identification du système de stockage au niveau du cluster ou de la SVM. Cependant, VASA Provider ne fonctionne qu'avec les identifiants au niveau du cluster.

*Étapes*

. Sur la page d'accueil des outils ONTAP, cliquez sur *Paramètres* > *Paramètres d'administration* > *configurer les informations d'identification par défaut pour le système de stockage*.
. Dans la boîte de dialogue informations d'identification par défaut du système de stockage, entrez le nom d'utilisateur et le mot de passe du système de stockage.
+
En fonction du nom d'utilisateur et du mot de passe, les informations d'identification du contrôleur de stockage sont attribuées dans ONTAP. Les identifiants du contrôleur de stockage peuvent être soit le compte d'administrateur, soit un compte personnalisé utilisant le contrôle d'accès basé sur des rôles (RBAC).

+
Vous ne pouvez pas utiliser VSC pour modifier les rôles associés à la paire nom d'utilisateur et mot de passe du contrôleur de stockage. Pour modifier ou créer un nouveau rôle utilisateur ONTAP à utiliser avec les outils ONTAP, vous pouvez utiliser System Manager.

+
Voir la link:..configure/task_configure_user_role_and_privileges.html["Configurez les rôles et privilèges utilisateur"]Dans la documentation _Outils ONTAP pour VMware vSphere_.

. Cliquez sur *OK* pour enregistrer les informations d'identification par défaut.


Si vous avez mis à jour les informations d'identification du système de stockage suite à la création d'un rapport sur un système de stockage `Authentication Failure` État, vous devez cliquer sur l'option *REDÉCOUVRIR TOUT* disponible sur la page systèmes de stockage. Dans ce cas, VSC tente de se connecter au système de stockage à l'aide des nouvelles informations d'identification.
