---
permalink: manage/task_configure_vasa_provider_to_use_ssh_for_remote_diag_access.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez configurer les outils ONTAP pour activer l"accès SSH pour l"utilisateur diag.' 
---
= Configurer l'accès aux diagnostics à distance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer les outils ONTAP pour activer l'accès SSH pour l'utilisateur diag.

*Ce dont vous aurez besoin*

L'extension VASA Provider doit être activée pour votre instance vCenter Server.

*À propos de cette tâche*

L'utilisation de SSH pour accéder au compte utilisateur diag présente les limites suivantes :

* Vous n'avez droit qu'à un seul compte de connexion par activation de SSH.
* L'accès SSH au compte utilisateur diag est désactivé lorsque l'une des conditions suivantes se produit :
+
** Le délai expire.
+
La session de connexion reste valide jusqu'à minuit le lendemain.

** Vous vous connectez à nouveau en tant qu'utilisateur diag à l'aide de SSH.




*Étapes*

. À partir du serveur vCenter, ouvrez une console pour accéder à la machine virtuelle de l'appliance ONTAP Tools.
. Connectez-vous en tant qu'utilisateur de maintenance.
. Entrez `4` Pour sélectionner support et Diagnostics.
. Entrez `3` Pour sélectionner Activer l'accès aux diagnostics à distance.
. Entrez `y` Dans la boîte de dialogue Confirmation pour activer l'accès au diagnostic à distance.
. Saisissez un mot de passe pour l'accès au diagnostic à distance.

