---
permalink: manage/task_collect_the_log_files.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez collecter les fichiers journaux des outils ONTAP® pour VMware vSphere à partir de l"option disponible dans l"interface graphique \(GUI\) de VSC. Le support technique peut vous demander de collecter les fichiers journaux afin de résoudre un problème.' 
---
= Collectez les fichiers journaux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez collecter les fichiers journaux des outils ONTAP pour VMware vSphere à partir de l'option disponible dans l'interface graphique de VSC. Le support technique peut vous demander de collecter les fichiers journaux afin de résoudre un problème.

*À propos de cette tâche*

Si vous avez besoin de fichiers journaux de VASA Provider, vous pouvez générer un bundle de support à partir de l'écran du panneau de configuration du fournisseur. Cette page fait partie des menus de maintenance de VASA Provider, accessibles depuis la console de l'appliance virtuelle.

`\https://vm_ip:9083`

Vous pouvez collecter les fichiers journaux VSC à l'aide de la fonctionnalité « Export VSC Logs » dans l'interface graphique de VSC. Lorsque vous collectez un bundle VSC Log avec VASA Provider activé, le bundle VSC Log propose également les journaux VP. La procédure suivante décrit comment collecter les fichiers journaux VSC :

*Étapes*

. Sur la page d'accueil des outils ONTAP, cliquez sur *Configuration* > *Exporter les journaux VSC*.
+
Cette opération peut prendre plusieurs minutes.

. Lorsque vous y êtes invité, enregistrez le fichier sur votre ordinateur local.
+
Vous pouvez ensuite envoyer le fichier _.zip_ au support technique.


