---
permalink: manage/task_change_the_administrative_password.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez modifier le mot de passe administrateur des outils ONTAP après le déploiement à l"aide de la console de maintenance.' 
---
= Modifiez le mot de passe administrateur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier le mot de passe administrateur des outils ONTAP après le déploiement à l'aide de la console de maintenance. Le mot de passe expire après 90 jours.


NOTE: Après avoir modifié le mot de passe administrateur dans la console de maintenance des outils ONTAP, si SRA est activé et configuré sur les outils ONTAP, exécutez la procédure *mise à jour des informations d'identification SRA* fournie dans link:../qsg.html["Aide à la vente des outils ONTAP pour VMware vSphere"] section. Le non-respect de ces instructions entraîne des erreurs signalées sur SRM.

*Étapes*

. Depuis vCenter Server, ouvrez une console pour accéder aux outils ONTAP.
. Connectez-vous en tant qu'utilisateur de maintenance.
. Entrez `1` Dans la console de maintenance pour sélectionner Configuration de l'application.
. Entrez `6` Pour sélectionner *Modifier le mot de passe utilisateur 'administrateur'*.
. Entrez un mot de passe de huit caractères minimum et de 30 caractères maximum. Le mot de passe doit contenir au moins un caractère supérieur, un chiffre inférieur, un chiffre et un caractère spécial. L'avertissement d'expiration du mot de passe s'affiche après 75 jours de réinitialisation du mot de passe. Le nouveau mot de passe ne peut pas être identique au dernier mot de passe utilisé.
+
Si vous ne suivez pas les recommandations relatives aux mots de passe, l'option de la console de maintenance se limite à modifier le mot de passe. Lorsque le mot de passe a expiré, vous êtes invité à le modifier.

. Entrez `y` dans la boîte de dialogue de confirmation.

