---
permalink: manage/task_resize_datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Le redimensionnement d"un datastore vous permet d"augmenter ou de réduire le stockage de vos fichiers de machine virtuelle. Vous devrez peut-être modifier la taille d"un datastore en fonction de l"évolution des besoins de votre infrastructure.' 
---
= Redimensionner les datastores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le redimensionnement d'un datastore vous permet d'augmenter ou de réduire le stockage de vos fichiers de machine virtuelle. Vous devrez peut-être modifier la taille d'un datastore en fonction de l'évolution des besoins de votre infrastructure.

*À propos de cette tâche*

Si vous souhaitez que les outils ONTAP redimensionnent le volume contenant lorsqu'il redimensionne le datastore VMFS, vous ne devez pas utiliser l'option *Use existing volume* (utiliser le volume existant) sous la section Storage Attributes (attributs de stockage) lors du provisionnement initial du datastore VMFS, mais vous devez plutôt le laisser créer automatiquement un nouveau volume pour chaque datastore.

Vous pouvez augmenter ou réduire la taille d'un datastore NFS, mais pour un datastore VMFS, vous ne pouvez augmenter la taille que. Le redimensionnement des datastores FlexGroup est également pris en charge avec l'option d'augmentation et de réduction automatiques. Un FlexGroup faisant partie d'un datastore traditionnel et d'un volume FlexVol qui fait partie d'un datastore vVols ne peuvent pas diminuer la taille existante, mais il peut atteindre une croissance de 120 % au maximum. Les snapshots par défaut sont activés sur ces volumes FlexGroup et FlexVol.


NOTE: Si vous utilisez toutes les plateformes de stockage de type SAN Array (ASA) avec ONTAP 9.9.1 ou version ultérieure, vous ne pouvez créer des datastores vvols avec une taille vmdk supérieure à 16 To.

*Étapes*

. Dans la page d'accueil de vSphere client, cliquez sur *hôtes et clusters*.
. Dans le volet de navigation, sélectionnez le centre de données qui contient le datastore.
. Cliquez avec le bouton droit de la souris sur le datastore et sélectionnez *NetApp ONTAP Tools* > *Assign QoS*.
. Dans la boîte de dialogue Redimensionner, spécifiez une nouvelle taille pour le datastore, puis cliquez sur *OK*.
+
Vous pouvez exécuter l'option *REDÉCOUVRIR TOUT* du menu systèmes de stockage pour mettre à jour manuellement la liste de stockage sous systèmes de stockage et tableau de bord, ou attendre la prochaine actualisation programmée.


